# Citizen Science Squash Bee Survey Distribution maps

# The first map (left panel) generated by this script highlights the counties from which 
# we recieved surveys AND reports of squash bees (grey), and counties from which recieved surveys
# but no reports of squash bees (black). The numbers on each county represent the number of surveys
# recieved from each county between 2017 and 2019. 

# The second map (right panel) generated by this script highlights the same counties as the
# left panel, but the numbers represent the numbers of DIFFERENT participants that submitted
# surveys from each county. 

rm(list=ls())
library(maps)
library(mapdata)
library(readxl)
data(countyMapEnv)

# Set working directory based on where the associated data is stored
setwd()

# Load county data
surv.counties <- data.frame(read_excel("CountiesSurvey.xlsx"))
View(surv.counties)

# To make a double panel map
op <- par(mfrow=c(1,2))


### Left map panel

# Set the margins
par(mar=c(0,0,0,0))

# Make generic Michigan county map; use following code color counties
# and add numbers
map('county', 'michigan', oma=c(0,0,0,0))


# Light gray counties had squash bees reported
# Black counties were counties from which surveys were recieved but no squash bees were reported

# To the right of the lines of code below, pseuodo code indicates if squash bee reports
# are new ("new": don't overlap with previous county records), when squash bee reports overlap with 
# previous county records (col=gray65, "reported previously": squash bees reported previously AND in our survey),
# or indicates counties with county records of squash bees from which we recieved surveys,
# but but no reports of squash bees (col=black, "reported previously": squash bees reported previously; 
# we recieved surveys but no squash bees reported).

# Previous county reports were obtained from the following publication:
#       Gibbs J, Ascher JS, Rightmyer MG, Isaacs R. 
#       The bees of Michigan (Hymenoptera: Apoidea: Anthophila) with notes on distribution, 
#       taxonomy, pollination, and natural history. Zootaxa. 2017; 4352(1): 001â€“160.

# The blue dots in the final publication figure denote all of the counties from which squash bees
# have been previously reported. These dots were added in Microsoft Powerpoint and will not appear
# on the figures generated by the code below. 

map("county", "michigan,allegan", col="gray65", fill=T, add=T) # new
map("county", "michigan,arenac", col="gray65", fill=T, add=T)
map("county", "michigan,alpena", col="black", fill=T, add=T)
map("county", "michigan,delta", col="black", fill=T, add=T)
map("county", "michigan,genesee", col="gray65", fill=T, add=T) # new
map("county", "michigan,grand traverse", col="gray65", fill=T, add=T) # new
map("county", "michigan,houghton", col="black", fill=T, add=T)
map("county", "michigan,isabella", col="gray65", fill=T, add=T) # reported previously
map("county", "michigan,kent", col="gray65", fill=T, add=T) # new
map("county", "michigan,lapeer", col="black", fill=T, add=T)
map("county", "michigan,leelanau", col="gray65", fill=T, add=T) # new
map("county", "michigan,livingston", col="gray65", fill=T, add=T) # new
map("county", "michigan,macomb", col="black", fill=T, add=T)
map("county", "michigan,montmorency", col="black", fill=T, add=T)
map("county", "michigan,muskegon", col="black", fill=T, add=T)
map("county", "michigan,oakland" ,col="gray65", fill=T, add=T) # reported previously
map("county", "michigan,ogemaw" ,col="black", fill=T, add=T) # reported previously
map("county", "michigan,ottawa", col="gray65", fill=T, add=T) # new
map("county", "michigan,shiawassee", col="black", fill=T, add=T)
map("county", "michigan,van buren", col="black", fill=T, add=T)
map("county", "michigan,wayne", col="gray65", fill=T, add=T) # reported previously

# Add number of surveys to counties 
text(surv.counties$Longitude,
     surv.counties$Latitude,
     surv.counties$NumSurveys,
     cex=0.8,
     col="white"
)




### Right map panel

# Set margins
par(mar=c(0,0,0,0))

# Map with survey counties highlighted and numbers of different participants per county
map('county', 'michigan', oma=c(0,0,0,0))


# Light gray counties had squash bees reported
# Black counties were counties from which surveys were recieved 
map("county", "michigan,allegan", col="gray65", fill=T, add=T) # new
map("county", "michigan,arenac", col="gray65", fill=T, add=T)
map("county", "michigan,alpena", col="black", fill=T, add=T)
map("county", "michigan,delta", col="black", fill=T, add=T)
map("county", "michigan,genesee", col="gray65", fill=T, add=T) # new
map("county", "michigan,grand traverse", col="gray65", fill=T, add=T) # new
map("county", "michigan,houghton", col="black", fill=T, add=T)
map("county", "michigan,isabella", col="gray65", fill=T, add=T) # reported previously
map("county", "michigan,kent", col="gray65", fill=T, add=T) # new
map("county", "michigan,lapeer", col="black", fill=T, add=T)
map("county", "michigan,leelanau", col="gray65", fill=T, add=T) # new
map("county", "michigan,livingston", col="gray65", fill=T, add=T) # new
map("county", "michigan,macomb", col="black", fill=T, add=T)
map("county", "michigan,montmorency", col="black", fill=T, add=T)
map("county", "michigan,muskegon", col="black", fill=T, add=T)
map("county", "michigan,oakland" ,col="gray65", fill=T, add=T) # reported previously
map("county", "michigan,ogemaw" ,col="black", fill=T, add=T) # reported previously
map("county", "michigan,ottawa", col="gray65", fill=T, add=T) # new
map("county", "michigan,shiawassee", col="black", fill=T, add=T)
map("county", "michigan,van buren", col="black", fill=T, add=T)
map("county", "michigan,wayne", col="gray65", fill=T, add=T) # reported previously

# Add number of different partcipants per county
text(surv.counties$Longitude,
     surv.counties$Latitude,
     surv.counties$NumDiffPar,
     cex=0.8,
     col="white"
)

par(op)

#This is the simplest level of map making in R - look at these pages for examples of all the other fancy things you can do
#https://www.molecularecologist.com/2012/09/making-maps-with-r/
#http://eriqande.github.io/rep-res-web/lectures/making-maps-with-R.html

