library(ordinal)
library(emmeans)
library(car)
library(RVAideMemoire)
rm(list=ls())
getwd()
newdata<-read.csv("BK1.csv",header = T)
summary(newdata)
newdata$BK1<-as.factor(newdata$BK1)
newdata$Sex.1M.2F<-as.factor(newdata$Sex.1M.2F)
newdata$Age1J.2Y.3S<-as.factor(newdata$Age1J.2Y.3S)
newdata$Village<-as.factor(newdata$Village)
modBK1<-clmm(BK1~Sex.1M.2F*Age1J.2Y.3S + (1|Village), data=newdata)
summary(modBK1)
RVAideMemoire::Anova.clmm(modBK1)
newdata

newdata<-read.csv("BK2.csv",header = T)
summary(newdata)
newdata$BK2<-as.factor(newdata$BK2)
newdata$Sex.1M.2F<-as.factor(newdata$Sex.1M.2F)
newdata$Age1J.2Y.3S<-as.factor(newdata$Age1J.2Y.3S)
newdata$Village<-as.factor(newdata$Village)
modBK2<-clmm(BK2~Sex.1M.2F*Age1J.2Y.3S + (1|Village), data=newdata)
summary(modBK2)
RVAideMemoire::Anova.clmm(modBK2)

newdata<-read.csv("BK3.csv",header = T)
summary(newdata)
newdata$BK3<-as.factor(newdata$BK3)
newdata$Sex.1M.2F<-as.factor(newdata$Sex.1M.2F)
newdata$Age1J.2Y.3S<-as.factor(newdata$Age1J.2Y.3S)
newdata$Village<-as.factor(newdata$Village)
modBK3<-clmm(BK3~Sex.1M.2F*Age1J.2Y.3S + (1|Village), data=newdata)
RVAideMemoire::Anova.clmm(modBK3)

newdata<-read.csv("BK4.csv",header = T)
summary(newdata)
newdata$BK4<-as.factor(newdata$BK4)
newdata$Sex.1M.2F<-as.factor(newdata$Sex.1M.2F)
newdata$Age1J.2Y.3S<-as.factor(newdata$Age1J.2Y.3S)
newdata$Village<-as.factor(newdata$Village)
modBK4<-clmm(BK4~Sex.1M.2F*Age1J.2Y.3S + (1|Village), data=newdata)
RVAideMemoire::Anova.clmm(modBK4)

newdata<-read.csv("BK5.csv",header = T)
summary(newdata)
newdata$BK5<-as.factor(newdata$BK5)
newdata$Sex.1M.2F<-as.factor(newdata$Sex.1M.2F)
newdata$Age1J.2Y.3S<-as.factor(newdata$Age1J.2Y.3S)
newdata$Village<-as.factor(newdata$Village)
modBK5<-clmm(BK5~Sex.1M.2F*Age1J.2Y.3S + (1|Village), data=newdata)
RVAideMemoire::Anova.clmm(modBK5)

newdata<-read.csv("BK6.csv",header = T)
summary(newdata)
newdata$BK6<-as.factor(newdata$BK6)
newdata$Sex.1M.2F<-as.factor(newdata$Sex.1M.2F)
newdata$Age1J.2Y.3S<-as.factor(newdata$Age1J.2Y.3S)
newdata$Village<-as.factor(newdata$Village)
modBK6<-clmm(BK6~Sex.1M.2F*Age1J.2Y.3S + (1|Village), data=newdata)
RVAideMemoire::Anova.clmm(modBK6)

newdata<-read.csv("BK7.csv",header = T)
summary(newdata)
newdata$BK7<-as.factor(newdata$BK7)
newdata$Sex.1M.2F<-as.factor(newdata$Sex.1M.2F)
newdata$Age1J.2Y.3S<-as.factor(newdata$Age1J.2Y.3S)
newdata$Village<-as.factor(newdata$Village)
modBK7<-clmm(BK7~Sex.1M.2F*Age1J.2Y.3S + (1|Village), data=newdata)
RVAideMemoire::Anova.clmm(modBK7)
emmeans(modBK7, pairwise~Age1J.2Y.3S, adjust="tukey")

newdata<-read.csv("BD1.csv",header = T)
summary(newdata)
newdata$BD1<-as.factor(newdata$BD1)
newdata$Sex.1M.2F<-as.factor(newdata$Sex.1M.2F)
newdata$Age1J.2Y.3S<-as.factor(newdata$Age1J.2Y.3S)
newdata$Village<-as.factor(newdata$Village)
modBD1<-clmm(BD1~Sex.1M.2F*Age1J.2Y.3S + (1|Village), data=newdata)
RVAideMemoire::Anova.clmm(modBD1)

newdata<-read.csv("BD2.csv",header = T)
summary(newdata)
newdata$BD2<-as.factor(newdata$BD2)
newdata$Sex.1M.2F<-as.factor(newdata$Sex.1M.2F)
newdata$Age1J.2Y.3S<-as.factor(newdata$Age1J.2Y.3S)
newdata$Village<-as.factor(newdata$Village)
modBD2<-clmm(BD2~Sex.1M.2F*Age1J.2Y.3S + (1|Village), data=newdata)
RVAideMemoire::Anova.clmm(modBD2)

newdata<-read.csv("BD3.csv",header = T)
summary(newdata)
newdata$BD3<-as.factor(newdata$BD3)
newdata$Sex.1M.2F<-as.factor(newdata$Sex.1M.2F)
newdata$Age1J.2Y.3S<-as.factor(newdata$Age1J.2Y.3S)
newdata$Village<-as.factor(newdata$Village)
modBD3<-clmm(BD3~Sex.1M.2F*Age1J.2Y.3S + (1|Village), data=newdata)
RVAideMemoire::Anova.clmm(modBD3)

newdata<-read.csv("HI1.csv",header = T)
summary(newdata)
newdata$HI1<-as.factor(newdata$HI1)
newdata$Sex.1M.2F<-as.factor(newdata$Sex.1M.2F)
newdata$Age1J.2Y.3S<-as.factor(newdata$Age1J.2Y.3S)
newdata$Village<-as.factor(newdata$Village)
modHI1<-clmm(HI1~Sex.1M.2F*Age1J.2Y.3S + (1|Village), data=newdata)
RVAideMemoire::Anova.clmm(modHI1)

newdata<-read.csv("HI2.csv",header = T)
summary(newdata)
newdata$HI2<-as.factor(newdata$HI2)
newdata$Sex.1M.2F<-as.factor(newdata$Sex.1M.2F)
newdata$Age1J.2Y.3S<-as.factor(newdata$Age1J.2Y.3S)
newdata$Village<-as.factor(newdata$Village)
modHI2<-clmm(HI2~Sex.1M.2F*Age1J.2Y.3S + (1|Village), data=newdata)
RVAideMemoire::Anova.clmm(modHI2)

newdata<-read.csv("CS1.csv",header = T)
summary(newdata)
newdata$CS1<-as.factor(newdata$CS1)
newdata$Sex.1M.2F<-as.factor(newdata$Sex.1M.2F)
newdata$Age1J.2Y.3S<-as.factor(newdata$Age1J.2Y.3S)
newdata$Village<-as.factor(newdata$Village)
modCS1<-clmm(CS1~Sex.1M.2F*Age1J.2Y.3S + (1|Village), data=newdata)
RVAideMemoire::Anova.clmm(modCS1)
emmeans(modCS1, pairwise~Sex.1M.2F*Age1J.2Y.3S, adjust="tukey")


newdata<-read.csv("CS2.csv",header = T)
summary(newdata)
newdata$CS2<-as.factor(newdata$CS2)
newdata$Sex.1M.2F<-as.factor(newdata$Sex.1M.2F)
newdata$Age1J.2Y.3S<-as.factor(newdata$Age1J.2Y.3S)
newdata$Village<-as.factor(newdata$Village)
modCS2<-clmm(CS2~Sex.1M.2F*Age1J.2Y.3S + (1|Village), data=newdata)
RVAideMemoire::Anova.clmm(modCS2)

newdata<-read.csv("CS3.csv",header = T)
summary(newdata)
newdata$CS3<-as.factor(newdata$CS3)
newdata$Sex.1M.2F<-as.factor(newdata$Sex.1M.2F)
newdata$Age1J.2Y.3S<-as.factor(newdata$Age1J.2Y.3S)
newdata$Village<-as.factor(newdata$Village)
modCS3<-clmm(CS3~Sex.1M.2F*Age1J.2Y.3S + (1|Village), data=newdata)
RVAideMemoire::Anova.clmm(modCS3)
emmeans(modCS3, pairwise~Sex.1M.2F*Age1J.2Y.3S, adjust="tukey")


newdata<-read.csv("AK1.csv",header = T)
summary(newdata)
newdata$AK1<-as.factor(newdata$AK1)
newdata$Sex.1M.2F<-as.factor(newdata$Sex.1M.2F)
newdata$Age1J.2Y.3S<-as.factor(newdata$Age1J.2Y.3S)
newdata$Village<-as.factor(newdata$Village)
modAK1<-clmm(AK1~Sex.1M.2F*Age1J.2Y.3S + (1|Village), data=newdata)
RVAideMemoire::Anova.clmm(modAK1)
emmeans(modAK1, pairwise~Age1J.2Y.3S, adjust="tukey")

newdata<-read.csv("AK2.csv",header = T)
summary(newdata)
newdata$AK2<-as.factor(newdata$AK2)
newdata$Sex.1M.2F<-as.factor(newdata$Sex.1M.2F)
newdata$Age1J.2Y.3S<-as.factor(newdata$Age1J.2Y.3S)
newdata$Village<-as.factor(newdata$Village)
modAK2<-clmm(AK2~Sex.1M.2F*Age1J.2Y.3S + (1|Village), data=newdata)
RVAideMemoire::Anova.clmm(modAK2)

newdata<-read.csv("AK3.csv",header = T)
summary(newdata)
newdata$AK3<-as.factor(newdata$AK3)
newdata$Sex.1M.2F<-as.factor(newdata$Sex.1M.2F)
newdata$Age1J.2Y.3S<-as.factor(newdata$Age1J.2Y.3S)
newdata$Village<-as.factor(newdata$Village)
modAK3<-clmm(AK3~Sex.1M.2F*Age1J.2Y.3S + (1|Village), data=newdata)
RVAideMemoire::Anova.clmm(modAK3)

newdata<-read.csv("AK4.csv",header = T)
summary(newdata)
newdata$AK4<-as.factor(newdata$AK4)
newdata$Sex.1M.2F<-as.factor(newdata$Sex.1M.2F)
newdata$Age1J.2Y.3S<-as.factor(newdata$Age1J.2Y.3S)
newdata$Village<-as.factor(newdata$Village)
modAK4<-clmm(AK4~Sex.1M.2F*Age1J.2Y.3S + (1|Village), data=newdata)
RVAideMemoire::Anova.clmm(modAK4)
emmeans(modAK4, pairwise~Age1J.2Y.3S, adjust="tukey")

newdata<-read.csv("AK5.csv",header = T)
summary(newdata)
newdata$AK5<-as.factor(newdata$AK5)
newdata$Sex.1M.2F<-as.factor(newdata$Sex.1M.2F)
newdata$Age1J.2Y.3S<-as.factor(newdata$Age1J.2Y.3S)
newdata$Village<-as.factor(newdata$Village)
modAK5<-clmm(AK5~Sex.1M.2F*Age1J.2Y.3S + (1|Village), data=newdata)
RVAideMemoire::Anova.clmm(modAK5)
emmeans(modAK5, pairwise~Age1J.2Y.3S, adjust="tukey")

kndata<-read.csv("knowledge.csv",header = T)
kndata$BK1<-as.factor(newdata$BK1)
kndata$Sex.1M.2F<-as.factor(newdata$Sex.1M.2F)
kndata$Age1J.2Y.3S<-as.factor(newdata$Age1J.2Y.3S)
kndata$Village<-as.factor(newdata$Village)
modBK1<-clmm(BK1~Sex.1M.2F*Age1J.2Y.3S + (1|Village), data=kndata)
RVAideMemoire::Anova.clmm(modBK1)