################################################################################
# From Balisi and Van Valkenburgh (2020) Communications Biology
# CODE FOR SUPPLEMENTARY FIGURE 2:
## Graphical representation of Supplementary Table 2: 
## histograms illustrating weak correlations between traits or trait combinations
## and some diversification rates
################################################################################


## all log files read below are generated by PyRate Covar analyses


## set up large multi-frame plot
library(scales)
par(mfrow=c(4, 6), mar=c(5, 5, 4, 0)+0.1, cex.lab=2, cex.axis=1.5)
cutscol = alpha(c("black", "white"), 0.5)[c(1, 2, 1)]


# Hesperocyoninae

hesp_covar_mass = read.csv("Hesperocyoninae_Covar_mass.log", sep="\\t")

hesp_mass_cov_sp = hist(hesp_covar_mass$cov_sp, plot=FALSE)
cuts = cutscol[cut(hesp_mass_cov_sp$breaks, c(-Inf, -0.6376, 2.1522, Inf))]
plot(hesp_mass_cov_sp, col=cuts, main="", xlab="", xlim=c(-4, 4), 
     border=alpha("black", 0.5))
abline(v=0)

hesp_mass_cov_ex = hist(hesp_covar_mass$cov_ex, plot=FALSE)
cuts = cutscol[cut(hesp_mass_cov_ex$breaks, c(-Inf, -0.6075, 2.1987, Inf))]
plot(hesp_mass_cov_ex, col=cuts, main="", xlab="", ylab="",
     border=alpha("black", 0.5), xlim=c(-4, 4))
abline(v=0)

hesp_covar_m1bs = read.csv("Hesperocyoninae_Covar_m1BS.log", sep="\\t")

hesp_m1bs_cov_sp = hist(hesp_covar_m1bs$cov_sp, plot=FALSE)
cuts = cutscol[cut(hesp_m1bs_cov_sp$breaks, c(-Inf, -0.6562, 2.1738, Inf))]
plot(hesp_m1bs_cov_sp, col=cuts, main="", xlab="", ylab="",
     border=alpha("black", 0.5), xlim=c(-4, 4))
abline(v=0)

hesp_m1bs_cov_ex = hist(hesp_covar_m1bs$cov_ex, plot=FALSE)
cuts = cutscol[cut(hesp_m1bs_cov_ex$breaks, c(-Inf, -0.5773, 2.2365, Inf))]
plot(hesp_m1bs_cov_ex, col=cuts, main="", xlab="", ylab="",
     border=alpha("black", 0.5), xlim=c(-3, 3))
abline(v=0)

hesp_covar_two = read.csv("Hesperoyoninae_Covar_twoTrait.log", sep="\\t")

hesp_two_cov_sp = hist(hesp_covar_two$cov_sp, plot=FALSE)
cuts = cutscol[cut(hesp_two_cov_sp$breaks, c(-Inf, -0.5936, 2.1998, Inf))]
plot(hesp_two_cov_sp, col=cuts, main="", xlab="", ylab="",
     border=alpha("black", 0.5), xlim=c(-4, 4))
abline(v=0)

hesp_two_cov_ex = hist(hesp_covar_two$cov_ex, plot=FALSE)
cuts = cutscol[cut(hesp_two_cov_ex$breaks, c(-Inf, -2.0053, 1.9019, Inf))]
plot(hesp_two_cov_ex, col=cuts, main="", xlab="", ylab="",
     border=alpha("black", 0.5), xlim=c(-4, 4))
abline(v=0)


# Borophaginae

boro_covar_mass = read.csv("Borophaginae_Covar_mass.log", sep="\\t")

boro_mass_cov_sp = hist(boro_covar_mass$cov_sp, plot=FALSE)
cuts = cutscol[cut(boro_mass_cov_sp$breaks, c(-Inf, -0.2423, 0.8444, Inf))]
plot(boro_mass_cov_sp, col=cuts, main="", xlab="",
     border=alpha("black", 0.5), xlim=c(-2, 2))
abline(v=0)

boro_mass_cov_ex = hist(boro_covar_mass$cov_ex, plot=FALSE)
cuts = cutscol[cut(boro_mass_cov_ex$breaks, c(-Inf, -0.2392, 0.8526, Inf))]
plot(boro_mass_cov_ex, col=cuts, main="", xlab="", ylab="",
     border=alpha("black", 0.5), xlim=c(-2, 2))
abline(v=0)

boro_covar_m1bs = read.csv("Borophaginae_Covar_m1BS.log", sep="\\t")

boro_m1bs_cov_sp = hist(boro_covar_m1bs$cov_sp, plot=FALSE)
cuts = cutscol[cut(boro_m1bs_cov_sp$breaks, c(-Inf, -0.2383, 0.8512, Inf))]
plot(boro_m1bs_cov_sp, col=cuts, main="", xlab="", ylab="",
     border=alpha("black", 0.5), xlim=c(-2, 2))
abline(v=0)

boro_m1bs_cov_ex = hist(boro_covar_m1bs$cov_ex, plot=FALSE)
cuts = cutscol[cut(boro_m1bs_cov_ex$breaks, c(-Inf, -0.2481, 0.8407, Inf))]
plot(boro_m1bs_cov_ex, col=cuts, main="", xlab="", ylab="",
     border=alpha("black", 0.5), xlim=c(-2, 2))
abline(v=0)

boro_covar_two = read.csv("Borophaginae_Covar_twoTrait.log", sep="\\t")

boro_two_cov_sp = hist(boro_covar_two$cov_sp, plot=FALSE)
cuts = cutscol[cut(boro_two_cov_sp$breaks, c(-Inf, -0.1632, 0.9278, Inf))]
plot(boro_two_cov_sp, col=cuts, main="", xlab="", ylab="",
     border=alpha("black", 0.5), xlim=c(-1.5, 1.5))
abline(v=0)

boro_two_cov_ex = hist(boro_covar_two$cov_ex, plot=FALSE)
cuts = cutscol[cut(boro_two_cov_ex$breaks, c(-Inf, -1.9942, 1.9218, Inf))]
plot(boro_two_cov_ex, col=cuts, main="", xlab="", ylab="",
     border=alpha("black", 0.5), xlim=c(-4, 4))
abline(v=0)


# Caninae

caninae_covar_mass = read.csv("Caninae_Covar_mass.log", sep="\\t")

caninae_mass_cov_sp = hist(caninae_covar_mass$cov_sp, plot=FALSE)
cuts = cutscol[cut(caninae_mass_cov_sp$breaks, c(-Inf, -0.3396, 1.6877, Inf))]
plot(caninae_mass_cov_sp, col=cuts, main="", xlab="",
     border=alpha("black", 0.5), xlim=c(-3, 3))
abline(v=0)

caninae_mass_cov_ex = hist(caninae_covar_mass$cov_ex, plot=FALSE)
cuts = cutscol[cut(caninae_mass_cov_ex$breaks, c(-Inf, -0.3473, 1.8331, Inf))]
plot(caninae_mass_cov_ex, col=cuts, main="", xlab="", ylab="",
     border=alpha("black", 0.5), xlim=c(-3, 3))
abline(v=0)

caninae_covar_m1bs = read.csv("Caninae_Covar_m1BS.log", sep="\\t")

caninae_m1bs_cov_sp = hist(caninae_covar_m1bs$cov_sp, plot=FALSE)
cuts = cutscol[cut(caninae_m1bs_cov_sp$breaks, c(-Inf, -0.3584, 1.6756, Inf))]
plot(caninae_m1bs_cov_sp, col=cuts, main="", xlab="", ylab="",
     border=alpha("black", 0.5), xlim=c(-3, 3))
abline(v=0)

caninae_m1bs_cov_ex = hist(caninae_covar_m1bs$cov_ex, plot=FALSE)
cuts = cutscol[cut(caninae_m1bs_cov_ex$breaks, c(-Inf, -0.34, 1.841, Inf))]
plot(caninae_m1bs_cov_ex, col=cuts, main="", xlab="", ylab="",
     border=alpha("black", 0.5), xlim=c(-3, 3))
abline(v=0)

caninae_covar_two = read.csv("Caninae_Covar_twoTrait.log", sep="\\t")

caninae_two_cov_sp = hist(caninae_covar_two$cov_sp, plot=FALSE)
cuts = cutscol[cut(caninae_two_cov_sp$breaks, c(-Inf, -0.1323, 1.8755, Inf))]
plot(caninae_two_cov_sp, col=cuts, main="", xlab="", ylab="",
     border=alpha("black", 0.5), xlim=c(-3, 3))
abline(v=0)

caninae_two_cov_ex = hist(caninae_covar_two$cov_ex, plot=FALSE)
cuts = cutscol[cut(caninae_two_cov_ex$breaks, c(-Inf, -1.947, 1.9747, Inf))]
plot(caninae_two_cov_ex, col=cuts, main="", xlab="", ylab="",
     border=alpha("black", 0.5), xlim=c(-4, 4))
abline(v=0)


# all Canidae

canidae_covar_mass = read.csv("allCanidae_Covar_mass.log", sep="\\t")

canidae_mass_cov_sp = hist(canidae_covar_mass$cov_sp, plot=FALSE)
cuts = cutscol[cut(canidae_mass_cov_sp$breaks, c(-Inf, -0.0917, 0.8721, Inf))]
plot(canidae_mass_cov_sp, col=cuts, main="", xlab="alpha_lambda",
     border=alpha("black", 0.5), xlim=c(-1.5, 1.5))
abline(v=0)

canidae_mass_cov_ex = hist(canidae_covar_mass$cov_ex, plot=FALSE)
cuts = cutscol[cut(canidae_mass_cov_ex$breaks, c(-Inf, -0.0508, 0.9418, Inf))]
plot(canidae_mass_cov_ex, col=cuts, main="", xlab="alpha_mu", ylab="",
     border=alpha("black", 0.5), xlim=c(-1.5, 1.5))
abline(v=0)

canidae_covar_m1bs = read.csv("allCanidae_Covar_m1BS.log", sep="\\t")

canidae_m1bs_cov_sp = hist(canidae_covar_m1bs$cov_sp, plot=FALSE)
cuts = cutscol[cut(canidae_m1bs_cov_sp$breaks, c(-Inf, -0.0891, 0.877, Inf))]
plot(canidae_m1bs_cov_sp, col=cuts, main="", xlab="alpha_lambda", ylab="",
     border=alpha("black", 0.5), xlim=c(-1.5, 1.5))
abline(v=0)

canidae_m1bs_cov_ex = hist(canidae_covar_m1bs$cov_ex, plot=FALSE)
cuts = cutscol[cut(canidae_m1bs_cov_ex$breaks, c(-Inf, -0.0564, 0.9451, Inf))]
plot(canidae_m1bs_cov_ex, col=cuts, main="", xlab="alpha_mu", ylab="",
     border=alpha("black", 0.5), xlim=c(-1.5, 1.5))
abline(v=0)

canidae_covar_two = read.csv("allCanidae_Covar_twoTrait.log", sep="\\t")

canidae_two_cov_sp = hist(canidae_covar_two$cov_sp, plot=FALSE)
cuts = cutscol[cut(canidae_two_cov_sp$breaks, c(-Inf, -0.0088, 0.9554, Inf))]
plot(canidae_two_cov_sp, col=cuts, main="", xlab="alpha_lambda", ylab="",
     border=alpha("black", 0.5), xlim=c(-1.5, 1.5))
abline(v=0)

canidae_two_cov_ex = hist(canidae_covar_two$cov_ex, plot=FALSE)
cuts = cutscol[cut(canidae_two_cov_ex$breaks, c(-Inf, -1.95, 1.9778, Inf))]
plot(canidae_two_cov_ex, col=cuts, main="", xlab="alpha_mu", ylab="",
     border=alpha("black", 0.5), xlim=c(-4, 4))
abline(v=0)