### Code to analyze color and abandonment data. Written by Conor Taff. 
##	Run in R version 3.3.3. Last updated on 1/11/2019. cct63@cornell.edu or cct663@gmail.com
	library(lme4)
	library(rethinking)
	library(blmeco)
	library(plotrix)
	library(MuMIn)
	library(sjPlot)
	library(optimx)

## Run a separate script that inputs the full set of RFID records and then calculated the number of visits
	## and unique visits for each day of the season rather than at a season long level. A second data frame
	## is also created that has the average and sd for unique visitors across days of the season.
	## This takea a few minutes to run because it is loading the big table of raw RFID reads.
	
	source('Code_Make_DailyRFID.r',print.eval=TRUE)

## Read in the master file that has every RFID read from all boxes for the entire
	## 2015 season in Ithaca.
		all<-d0		# Depends on the script above having been run already
		all.orig<-all	# saving this version unmodified
		# Saving separate subsets for the two sites
			all.cu2<-subset(all,all$Site=="Unit 2")
			all.cu4<-subset(all,all$Site=="Unit 4")
		all<-all.orig		# Change here if you want to run separately for sites
		
## Read in other files. First is main data with treatments, etc. Second two are generated by script
	## run in line 12 above.
		main.d<-read.delim("Input_Main_Data.txt")
		day.d<-read.csv("Input_Visits_By_Day.csv")
		day.av.d<-read.csv("Input_Avg_Daily_Visits.csv")
		day.av.d$UnitBox<-gsub("-","_",day.av.d$UnitBox)
		colnames(day.av.d)[2]<-"unitbox"
		main.d<-join(main.d,day.av.d,"unitbox")
		
## This calculates and plots the total number of RFID reads on every day of the season pooling all units.
		date<-as.data.frame(seq(min(all$JDate),max(all$JDate),by=1))
		colnames(date)<-"JDate"
		for(i in 1:nrow(date)){
			date$Count[i]<-nrow(subset(all.orig,all.orig$JDate==date$JDate[i]))
		}
		pdf("Output_Fig_Total_RFID_Reads.pdf",width=11,height=5)
			plot(date$JDate,date$Count,xlab="Julian Date",ylab="Total RFID Reads",
					pch=16,main="Ithaca",xaxt="n")
			lines(date$JDate,date$Count,lwd=2,col="black")
			text(176,200000,"Total of 2,433,455 reads")
			axis(1,at=seq(120,190,2))
		dev.off()

## Make a figure that shows the number of active PIT tags and RFIDs on each day of season
	## Generate counts for how many unique birds were observed on any RFID on each day
		# of the breeding season.
			all.rfid<-as.data.frame(unique(all$RFID))
			colnames(all.rfid)<-c("RFID")	
			for(i in 1:nrow(all.rfid)){
				sub<-subset(all,all$RFID==all.rfid$RFID[i])
				all.rfid$First[i]<-min(na.omit(sub$JDate))
				all.rfid$Second[i]<-max(na.omit(sub$JDate))
			}
			all.rfid$Diff<-all.rfid$Second-all.rfid$First
			dates<-as.data.frame(seq(min(all.rfid$First),max(all.rfid$Second),1))
			colnames(dates)<-"JDate"
			for(i in 1:nrow(dates)){
				dates$Count[i]<-nrow(subset(all.rfid,all.rfid$First<dates$JDate[i]&
					all.rfid$Second>dates$JDate[i]))
			}	
		pdf("Output_Fig_Active_Tags.pdf",width=6,height=6)	
			plot(dates$JDate,dates$Count,xlab="Julian Date",ylab="Count",
				pch=16,xlim=c(135,185),ylim=c(0,100),main="")
			lines(dates$JDate,dates$Count,lwd=2,col="black")
			#barplot(dates$Count)
			#axis(1,at=c(-10,100),labels=FALSE)
	## Generate counts for the number of RFID units running on each day of the breeding season
			all.unit<-as.data.frame(unique(all$UnitBox))
			colnames(all.unit)<-c("UnitBox")	
			for(i in 1:nrow(all.unit)){
				sub<-subset(all,all$UnitBox==all.unit$UnitBox[i])
				all.unit$First[i]<-min(na.omit(sub$JDate))
				all.unit$Second[i]<-max(na.omit(sub$JDate))
			}
			all.unit$Diff<-all.unit$Second-all.unit$First
			dates2<-as.data.frame(seq(min(all.unit$First),max(all.unit$Second),1))
			colnames(dates2)<-"JDate"
			for(i in 1:nrow(dates2)){
				dates2$Count[i]<-nrow(subset(all.unit,all.unit$First<dates2$JDate[i]&
					all.unit$Second>dates2$JDate[i]))
			}		
			points(dates2$JDate,dates2$Count,xlab="Julian Date",ylab="Number of active RFID units",
				col="slateblue",pch=16)
			lines(dates2$JDate,dates2$Count,lwd=2,col="slateblue")
			legend("topleft",c("Active PITs","Active RFID"),lwd=2,col=c("Black","Slateblue"))
			#barplot(dates2$Count)
			#axis(1,at=c(-10,100),labels=FALSE)
			dev.off()

## Make a plot showing number of active PIT tags in a different way			
	## Plot number of PITs a different way
		pdf("Output_Fig_Active_PIT.pdf",width=5.7,height=9.1)
		all.rfid$seq<-seq(1,nrow(all.rfid),1)
		plot(1,1,xlim=c(min(all.rfid$First),max(all.rfid$Second)),ylim=c(0,nrow(all.rfid)),type="n",yaxt="n",
			xlab="Julian Date",ylab="Individual Birds (one per line)",main="Active PITs")
		for(i in 1:nrow(all.rfid)){
			lines(c(all.rfid$First[i],all.rfid$Second[i]),rep(all.rfid$seq[i],2))
		}
		dev.off()
		
## Calculate number of trips for every day that PIT was detected for each bird
	trips<-NA
	temp<-NA
	all2<-subset(all,all$focal=="No")
	for(i in 1:nrow(all.rfid)){
		for(k in 1:all.rfid[i,4]){
			temp[k]<-paste(all.rfid[i,1],all.rfid[i,3]+k-1,sep="_")
		}
		trips<-append(trips,temp)
	}
	trips<-trips[2:length(trips)]
	trips<-as.data.frame(trips)
	for(i in 1:nrow(trips)){
		trips$RFID[i]<-strsplit(as.character(trips$trips[i]),"_")[[1]][1]
		trips$JDate[i]<-strsplit(as.character(trips$trips[i]),"_")[[1]][2]
		}
	trips$trips<-as.character(trips$trips)
	colnames(trips)[1]<-"fRFID_Day"
	for(i in 1:nrow(trips)){
		sub<-subset(all2,as.character(all2$RFID)==as.character(trips$RFID[i])&
			as.character(all2$JDate)==as.character(trips$JDate[i]))
		trips$TRIP[i]<-length(unique(sub$Visited.ubd))
		print(paste(i," of ",nrow(trips),sep=""))
	}
	

## Analyze likelihood of nest failure by treatment	
	abd<-as.data.frame(matrix(nrow=3,ncol=2))
	colnames(abd)<-c("Hatched","Failed")
	rownames(abd)<-c("Control","Low FR","High FR")
	abd[,1]<-c(12,9,4)
	abd[,2]<-c(3,4,8)
	se<-c(1.96*sqrt((1/15)*.8*(1-.8)),
		1.96*sqrt((1/13)*(9/13)*(1-(9/13))),
		1.96*sqrt((1/12)*(4/12)*(1-(4/12)))
		)
	
	pdf("Output_Fig1a.pdf",width=4.5,height=5.25)
		#par(mfrow=c(1,2))
		barplot(c(12/15,9/13,4/12),xlim=c(0,3.5),ylim=c(0,1),ylab="Successfully hatched nests (%)",yaxt="n")
		axis(1,at=c(-1,.7,1.9,3.1,5),labels=c("","Control","Low FR","High FR",""))
		axis(2,at=c(0,0.25,0.5,0.75,1),labels=c("0","25","50","75","100"))
		lines(rep(0.7,2),c(12/15+se[1],12/15-se[1]))
		lines(rep(1.9,2),c(9/13+se[2],9/13-se[2]))
		lines(rep(3.1,2),c(4/12+se[3],4/12-se[3]))
		corner.label("(A)")

	dev.off()
	m<-glm(failedinc~treatment,data=main.d,family=binomial)
	
	pdf("Output_Fig1b.pdf",width=5.5,height=5.25)
## Analyze female mass by treatment across the three captures

	hhs<-c(mean(na.omit(subset(main.d$mass1,main.d$treatment=="Control"))),
		mean(na.omit(subset(main.d$mass1,main.d$treatment=="Low Tape"))),
		mean(na.omit(subset(main.d$mass1,main.d$treatment=="High Tape"))),
		0,
		mean(na.omit(subset(main.d$mass2,main.d$treatment=="Control"))),
		mean(na.omit(subset(main.d$mass2,main.d$treatment=="Low Tape"))),
		mean(na.omit(subset(main.d$mass2,main.d$treatment=="High Tape"))),
		0,
		mean(na.omit(subset(main.d$mass3,main.d$treatment=="Control"))),
		mean(na.omit(subset(main.d$mass3,main.d$treatment=="Low Tape"))),
		mean(na.omit(subset(main.d$mass3,main.d$treatment=="High Tape"))))
		
	hhs2<-hhs[c(1:3,5:7,9:11)]
		
	ses<-c(sd(na.omit(subset(main.d$mass1,main.d$treatment=="Control"))),
		sd(na.omit(subset(main.d$mass1,main.d$treatment=="Low Tape"))),
		sd(na.omit(subset(main.d$mass1,main.d$treatment=="High Tape"))),
		sd(na.omit(subset(main.d$mass2,main.d$treatment=="Control"))),
		sd(na.omit(subset(main.d$mass2,main.d$treatment=="Low Tape"))),
		sd(na.omit(subset(main.d$mass2,main.d$treatment=="High Tape"))),
		sd(na.omit(subset(main.d$mass3,main.d$treatment=="Control"))),
		sd(na.omit(subset(main.d$mass3,main.d$treatment=="Low Tape"))),
		sd(na.omit(subset(main.d$mass3,main.d$treatment=="High Tape"))))
	
	#pdf("Output_Fig1b.pdf",width=4.7,height=5.25)	
	#barplot(hhs,space=0,ylim=c(0,25),col=rep(c("gray20","gray60","gray90","white"),3),
	#	ylab="Female mass (g)")
	#axis(1,at=c(-1,1.5,5.5,9.5,14),labels=c("","Pre-Treatment","Recapture 1","Recapture 2",""))
	#xloc<-c(.5,1.5,2.5,4.5,5.5,6.5,8.5,9.5,10.5)
	xloc<-c(1,2,3,6,7,8,11,12,13)
	
	jit<-0.11
	con<-subset(main.d,main.d$treatment=="Control")
	lfr<-subset(main.d,main.d$treatment=="Low Tape")
	hfr<-subset(main.d,main.d$treatment=="High Tape")
	plot(rep(1,nrow(con))+runif(nrow(con),-jit,jit),con$mass1,pch=21,bg="gray40",xlim=c(0,14),
		ylim=c(16,26),yaxt="n",xaxt="n",ylab="Mass (g)",bty="n",xlab="")
	points(rep(2,nrow(lfr))+runif(nrow(lfr),-jit,jit),lfr$mass1,pch=21,bg="orange")
	points(rep(3,nrow(hfr))+runif(nrow(hfr),-jit,jit),hfr$mass1,pch=21,bg="sky blue")
	
	points(rep(6,nrow(con))+runif(nrow(con),-jit,jit),con$mass2,pch=21,bg="gray40")
	points(rep(7,nrow(lfr))+runif(nrow(lfr),-jit,jit),lfr$mass2,pch=21,bg="orange")
	points(rep(8,nrow(hfr))+runif(nrow(hfr),-jit,jit),hfr$mass2,pch=21,bg="sky blue")
	
	points(rep(11,nrow(con))+runif(nrow(con),-jit,jit),con$mass3,pch=21,bg="gray40")
	points(rep(12,nrow(lfr))+runif(nrow(lfr),-jit,jit),lfr$mass3,pch=21,bg="orange")
	points(rep(13,nrow(hfr))+runif(nrow(hfr),-jit,jit),hfr$mass3,pch=21,bg="sky blue")
	
	#lines(c(3,8),rep(25,2))
	#lines(rep(3,2),c(25,24.7))
	#lines(rep(8,2),c(25,22))
	#text(5.5,25.3,"* P = 0.01")
	for(i in 1:9){
		lines(rep(xloc[i]+.3,2),c(hhs2[i]+ses[i],hhs2[i]-ses[i]))
	}
	
	axis(2,at=c(0,16,18,20,22,24,26,28))
	axis(1,at=c(-1,2,7,12,18),labels=c("","First Capture","Second Capture","Third Capture",""))
	
	points(xloc+.3,hhs[c(1:3,5:7,9:11)],pch=15)
	legend("topright",c("Control","Low FR","High FR"),pch=21,pt.bg=c("gray40","orange","sky blue"),bty="n")
	
		
	corner.label("(B)")
	dev.off()
	
	summary(md1<-lm(mass2~treatment+mass1,data=main.d))
	summary(md2<-lm(mass3~treatment+mass1,data=main.d))
	
	m1<-lm(mass1~treatment,data=main.d)
	m2<-lm(mass2~treatment,data=main.d)
	m3<-lm(mass3~treatment,data=main.d)
	TukeyHSD(aov(m2))
	TukeyHSD(aov(m1))
	TukeyHSD(aov(m3))
	
	
## Check for differences in base and stress cort after treatments

	m1<-lm(pre.base~treatment,data=main.d)
	m2<-lm(post.base~treatment,data=main.d)
	m3<-lm(post2.base~treatment,data=main.d)
	
	m4<-lm(pre.s.resp~treatment,data=main.d)
	m6<-lm(post2.s.resp~treatment,data=main.d)


## Check for influence of coloration on abandonment

	modlist<-c("failedinc~treatment+b.total.bright+b.total.bright*treatment",
		"failedinc~treatment+b.total.bright",
		"failedinc~treatment","failedinc~1",
		"failedinc~treatment+r.h.theta+r.h.theta*treatment",
		"failedinc~treatment+r.h.theta",
		"failedinc~treatment+r.r.achieved+r.r.achieved*treatment",
		"failedinc~treatment+r.r.achieved")
		
	main.d2<-main.d[,c("unitbox","failedinc","treatment","b.total.bright","r.h.theta","r.r.achieved")]
	main.d2<-na.omit(main.d2)

	m1<-glm(failedinc~treatment+b.total.bright+b.total.bright*treatment,data=main.d2,family=binomial)
	m2<-glm(failedinc~treatment+b.total.bright,data=main.d2,family=binomial)
	m3<-glm(failedinc~treatment,data=main.d2,family=binomial)
	m4<-glm(failedinc~1,data=main.d2,family=binomial)
	m5<-glm(failedinc~treatment+r.h.theta+r.h.theta*treatment,data=main.d2,family=binomial)
	m6<-glm(failedinc~treatment+r.h.theta,data=main.d2,family=binomial)
	m7<-glm(failedinc~treatment+r.r.achieved+r.r.achieved*treatment,data=main.d2,family=binomial)
	m8<-glm(failedinc~treatment+r.r.achieved,data=main.d2,family=binomial)
	
	mod.output<-list(m1,m2,m3,m4,m5,m6,m7,m8)
	
	AICtab<-as.data.frame(modlist)
		for(j in 1:nrow(AICtab)){
			AICtab$AICc[j]<-AICc(mod.output[[j]])
			AICtab$LL[j]<-logLik(mod.output[[j]])
			AICtab$K[j]<-attr(logLik(mod.output[[j]]),"df")
		}
		minim<-min(AICtab$AICc)
		AICtab$D.AICc<-AICtab$AICc-minim
		AICtab$rellik<-exp(-.5* AICtab$D.AICc)
		sumAICs<-sum(AICtab$rellik)
		for(u in 1:nrow(AICtab)){
			AICtab$Wi[u]<-round(AICtab$rellik[u]/sumAICs,2)
		}
		AICtab<-AICtab[order(-AICtab$rellik),]
		
	write.csv(AICtab,"Output_Nest_Fail_AIC.csv")
	
	


### Plot failed vs. hatched by color for each treatment group

	hgs<-c(mean(na.omit(subset(main.d$b.total.bright,main.d$treatment=="Control"&main.d$failedinc=="Hatch"))),
		mean(na.omit(subset(main.d$b.total.bright,main.d$treatment=="Control"&main.d$failedinc=="Fail"))),
		0,
		mean(na.omit(subset(main.d$b.total.bright,main.d$treatment=="Low Tape"&main.d$failedinc=="Hatch"))),
		mean(na.omit(subset(main.d$b.total.bright,main.d$treatment=="Low Tape"&main.d$failedinc=="Fail"))),
		0,
		mean(na.omit(subset(main.d$b.total.bright,main.d$treatment=="High Tape"&main.d$failedinc=="Hatch"))),
		mean(na.omit(subset(main.d$b.total.bright,main.d$treatment=="High Tape"&main.d$failedinc=="Fail"))))
		
	sds<-c(sd(na.omit(subset(main.d$b.total.bright,main.d$treatment=="Control"&main.d$failedinc=="Hatch")))/sqrt(12),
		sd(na.omit(subset(main.d$b.total.bright,main.d$treatment=="Control"&main.d$failedinc=="Fail")))/sqrt(3),
		sd(na.omit(subset(main.d$b.total.bright,main.d$treatment=="Low Tape"&main.d$failedinc=="Hatch")))/sqrt(9),
		sd(na.omit(subset(main.d$b.total.bright,main.d$treatment=="Low Tape"&main.d$failedinc=="Fail")))/sqrt(4),
		sd(na.omit(subset(main.d$b.total.bright,main.d$treatment=="High Tape"&main.d$failedinc=="Hatch")))/sqrt(4),
		sd(na.omit(subset(main.d$b.total.bright,main.d$treatment=="High Tape"&main.d$failedinc=="Fail")))/sqrt(8))
		
	pdf("Output_Fig2.pdf",width=4.5,height=5)	
	#barplot(hgs,space=0,col=c("gray40","gray80","white","gray40","gray80","white","gray40","gray80"),ylim=c(0,60),
	#	ylab="Mean breast brightness (%)",xlim=c(0,8))
	#legend("topleft",c("Hatch","Fail"),fill=c("gray40","gray80"))
	
	#axis(1,at=c(-1,1,4,7,9),labels=c("","Control","Low FR","High FR",""))
	
	jit2<-0.1
	con1<-subset(con,con$failedinc=="Hatch")
	con2<-subset(con,con$failedinc=="Fail")
	plot(rep(1,nrow(con1))+runif(nrow(con1),-jit2,jit2),con1$b.total.bright,pch=21,bg="gray90",bty="n",xaxt="n",
		yaxt="n",ylab="Mean breast brightness (%)",xlab="",xlim=c(0,9),ylim=c(20,60))
	axis(1,at=c(-1,1.5,4.5,7.5,12),labels=c("","Control","Low FR","High FR",""))
	axis(2,at=c(0,20,25,30,35,40,45,50,55,100))
	points(rep(2,nrow(con2))+runif(nrow(con2),-jit2,jit2),con2$b.total.bright,pch=21,bg="gray90")
	
	lfr1<-subset(lfr,lfr$failedinc=="Hatch")
	lfr2<-subset(lfr,lfr$failedinc=="Fail")
	points(rep(4,nrow(lfr1))+runif(nrow(lfr1),-jit2,jit2),lfr1$b.total.bright,pch=21,bg="gray60")
	points(rep(5,nrow(lfr2))+runif(nrow(lfr2),-jit2,jit2),lfr2$b.total.bright,pch=21,bg="gray60")
	
	hfr1<-subset(hfr,hfr$failedinc=="Hatch")
	hfr2<-subset(hfr,hfr$failedinc=="Fail")
	points(rep(7,nrow(hfr1))+runif(nrow(hfr1),-jit2,jit2),hfr1$b.total.bright,pch=21,bg="white")
	points(rep(8,nrow(hfr2))+runif(nrow(hfr2),-jit2,jit2),hfr2$b.total.bright,pch=21,bg="white")
	
	xlocs<-c(1,2,4,5,7,8)
	hgs2<-hgs[c(1:2,4:5,7:8)]
	for(i in 1:6){
		lines(rep(xlocs[i],2)+.12,c(hgs2[i]+sds[i],hgs2[i]-sds[i]))
	}
	
	points(xlocs+.12,hgs2,pch=15)
	
	hgs2<-hgs[c(1:2,4:5,7:8)]
	xloc<-c(.5,1.5,3.5,4.5,6.5,7.5)
	h<-2
	text(xloc[1],h,"12",col="white")
	text(xloc[2],h,"3")
	text(xloc[3],h,"9",col="white")
	text(xloc[4],h,"4")
	text(xloc[5],h,"4",col="white")
	text(xloc[6],h,"8")
	
	for(i in 1:6){
		lines(rep(xloc[i],2),c(hgs2[i]+sds[i],hgs2[i]-sds[i]))
	}
	dev.off()
	
### New figure version

	pdf("Output_Figure2.pdf",width=6.5,height=6.5)	
			post<-as.data.frame(mvrnorm(100000,coef(m1),vcov(m1)))
		r<-seq(0,100,.1)
		r.con<-sapply(r,function(z)logistic(coef(m1)[1]+coef(m1)[4]*z))
		con.ci<-sapply(r,function(z)HPDI(logistic(post[,1]+post[,4]*z),prob=0.9))
		plot(r,r.con,ylim=c(0,100),type="n",xlim=c(22,55),ylab="Likelihood of hatching (%)",
			xlab="Mean breast brightness (%)")
		lines(r,r.con*100,lwd=2,col="black")
		con.ci<-con.ci*100
		#shade(con.ci,r,col=col.alpha("black",0.1))
		r.lfr<-sapply(r,function(z)mean(logistic(coef(m1)[1]+coef(m1)[3]+coef(m1)[4]*z+coef(m1)[6]*z)))
		lfr.ci<-sapply(r,function(z)HPDI(logistic(post[,1]+post[,3]+post[,4]*z+post[,6]*z),prob=0.9))
		lfr.ci<-lfr.ci*100
		#shade(lfr.ci,r,col=col.alpha("orange",0.2))
		lines(r,r.lfr*100,lwd=2,col="orange")
		r.hfr<-sapply(r,function(z)mean(logistic(coef(m1)[1]+coef(m1)[2]+coef(m1)[4]*z+coef(m1)[5]*z)))
		hfr.ci<-sapply(r,function(z)HPDI(logistic(post[,1]+post[,2]+post[,4]*z+post[,5]*z),prob=0.9))
		lines(r,r.hfr*100,lwd=2,col="sky blue")
		hfr.ci<-hfr.ci*100
		#shade(hfr.ci,r,col=col.alpha("sky blue",0.3))
		jit3<-2
		points(con1$b.total.bright,rep(100,nrow(con1))+runif(nrow(con1),-jit3,jit3),pch=21,bg="gray40")
		points(con2$b.total.bright,rep(0,nrow(con2))+runif(nrow(con2),-jit3,jit3),pch=21,bg="gray40")
		
		points(lfr1$b.total.bright,rep(100,nrow(lfr1))+runif(nrow(lfr1),-jit3,jit3),pch=21,bg="orange")
		points(lfr2$b.total.bright,rep(0,nrow(lfr2))+runif(nrow(lfr2),-jit3,jit3),pch=21,bg="orange")
		points(hfr1$b.total.bright,rep(100,nrow(hfr1))+runif(nrow(hfr1),-jit3,jit3),pch=21,bg="sky blue")
		points(hfr2$b.total.bright,rep(0,nrow(hfr2))+runif(nrow(hfr2),-jit3,jit3),pch=21,bg="sky blue")
		legend(48,25,c("Control","Low FR","High FR"),pch=21,pt.bg=c("gray40","orange","sky blue"),
			lwd=2,bty="n",col=c("gray40","orange","sky blue"))
	dev.off()
			
	
### Test for relationship between daily unique visitors and coloration

	day.d$UBox<-as.character(day.d$UnitBox)
	day.d$UBox<-gsub("-","_",day.d$UBox)
	main.d$UBox<-as.character(main.d$unitbox)
	colnames(dates)<-c("JDate","ActivePIT")
	
	d3<-join(day.d,main.d,"UBox")
	for(i in 1:nrow(d3)){
		d3$JDate[i]<-strsplit(as.character(d3$Visited.ubd[i]),"_")[[1]][3]
	}
	
	dat3<-join(d3,dates,"JDate")
	dat3<-subset(dat3,is.na(dat3$Visited.ubd)==FALSE)
	dat3$Offset<-as.numeric(dat3$JDate)-dat3$cap.jdate1
		
	dat3<-dat3[,c("JDate","All.m","Uni.m","All.f","Uni.f","All.t","Uni.t","All.v","All.u","b.total.bright","r.h.theta",
		"r.r.achieved","Offset","ActivePIT","treatment","UnitBox")]

	dat3<-na.omit(dat3)
	
	own<-subset(all,as.character(all$RFID)==as.character(all$FemaleRFID))
	#for(i in 1:nrow(dat3)){
	#	sub<-subset(own,own$JDate==dat3$JDate[i]&own$UnitBox==dat3$UnitBox)
	#	dat3$SelfReads[i]<-nrow(sub)
	#	print(paste(i," of ",nrow(dat3),sep=""))
	#}
	#dat3<-subset(dat3,dat3$SelfReads>1)
	dat3.save<-dat3
	for(i in 1:nrow(dat3)){
		if(dat3$Offset[i]<0){dat3$Offset2[i]<-"A"}
		if(dat3$Offset[i]>-1&dat3$Offset[i]<8){dat3$Offset2[i]<-"B"}
		if(dat3$Offset[i]>7&dat3$Offset[i]<15){dat3$Offset2[i]<-"C"}
		if(dat3$Offset[i]>15){dat3$Offset2[i]<-"D"}
	}
	dat3$b.total.bright<-scale(dat3$b.total.bright)
	dat3$Offset<-scale(dat3$Offset)
	dat3$ActivePIT<-scale(dat3$ActivePIT)
	dat3$Index<-seq(1,nrow(dat3),1)
	#dat3$SelfReads<-scale(dat3$SelfReads)
	dat3$r.r.achieved<-scale(dat3$r.r.achieved)
	dat3$r.h.theta<-scale(dat3$r.h.theta)
	
	modlist<-c("~1","~treatment+offset2",
		"~breast+offset2","~breast+treatment+offset2","~breast*treatment+offset2",
		"~theta+offset2","~theta+treatment+offset2","~theta*treatment+offset2",
		"~ra+offset2","~ra+treatment+offset2","~ra*treatment+offset2")	
	
	dat3$resp<-dat3$All.u  # Change response here to run 'uni.m' or 'uni.f' for male/female
	
	m.1<-glmer(resp~1+(1|UnitBox)+(1|JDate),data=dat3,family=poisson)
	m.2<-glmer(resp~treatment+Offset2+(1|UnitBox)+(1|JDate),data=dat3,family=poisson,
		control=glmerControl(optimizer="optimx",optCtrl=list(method="nlminb")))
	m.3<-glmer(resp~b.total.bright+Offset2+(1|UnitBox)+(1|JDate),data=dat3,family=poisson,
		control=glmerControl(optimizer="optimx",optCtrl=list(method="nlminb")))
	m.4<-glmer(resp ~b.total.bright+treatment+Offset2+(1|UnitBox)+(1|JDate),data=dat3,family=poisson,
		control=glmerControl(optimizer="optimx",optCtrl=list(method="nlminb")))
	m.5<-glmer(resp ~b.total.bright+treatment+b.total.bright*treatment+Offset2+(1|UnitBox)+(1|JDate),
		data=dat3,family=poisson,control=glmerControl(optimizer="optimx",optCtrl=list(method="nlminb")))
	m.6<-glmer(resp ~r.h.theta+Offset2+(1|UnitBox)+(1|JDate),data=dat3,family=poisson,
		control=glmerControl(optimizer="optimx",optCtrl=list(method="nlminb")))
	m.7<-glmer(resp ~r.h.theta+treatment+Offset2+(1|UnitBox)+(1|JDate),data=dat3,family=poisson,
		control=glmerControl(optimizer="optimx",optCtrl=list(method="nlminb")))
	m.8<-glmer(resp ~r.h.theta+treatment+r.h.theta*treatment+Offset2+(1|UnitBox)+(1|JDate),data=dat3,family=poisson,
		control=glmerControl(optimizer="optimx",optCtrl=list(method="nlminb")))
	m.9<-glmer(resp ~r.r.achieved+Offset2+(1|UnitBox)+(1|JDate),data=dat3,family=poisson,
		control=glmerControl(optimizer="optimx",optCtrl=list(method="nlminb")))
	m.10<-glmer(resp ~r.r.achieved+treatment+Offset2+(1|UnitBox)+(1|JDate),data=dat3,family=poisson,
		control=glmerControl(optimizer="optimx",optCtrl=list(method="nlminb")))
	m.11<-glmer(resp ~r.r.achieved+treatment+r.r.achieved*treatment+Offset2+(1|UnitBox)+(1|JDate),data=dat3,family=poisson,
		control=glmerControl(optimizer="optimx",optCtrl=list(method="nlminb")))
	
	mod.output<-list(m.1,m.2,m.3,m.4,m.5,m.6,m.7,m.8,m.9,m.10,m.11)
	
	AICtab<-as.data.frame(modlist)
		for(j in 1:nrow(AICtab)){
			AICtab$AICc[j]<-AICc(mod.output[[j]])
			AICtab$LL[j]<-logLik(mod.output[[j]])
			AICtab$K[j]<-attr(logLik(mod.output[[j]]),"df")
		}
		minim<-min(AICtab$AICc)
		AICtab$D.AICc<-AICtab$AICc-minim
		AICtab$rellik<-exp(-.5* AICtab$D.AICc)
		sumAICs<-sum(AICtab$rellik)
		for(u in 1:nrow(AICtab)){
			AICtab$Wi[u]<-round(AICtab$rellik[u]/sumAICs,2)
		}
		AICtab<-AICtab[order(-AICtab$rellik),]
		
	m.5.vis<-m.5

### Fit the same candidate model set but to trips, uses different optimizer.		
		
	dat3$resp<-dat3$Uni.t
	
	dat3.2<-subset(dat3,dat3$Offset2!="A")
	m.1<-glmer(resp~1+(1|UnitBox)+(1|JDate),data=dat3.2,family=poisson)
	m.2<-glmer(resp~treatment+ Offset2+(1|UnitBox)+(1|JDate),data=dat3.2,family=poisson)
	m.3<-glmer(resp~b.total.bright+ Offset2+(1|UnitBox)+(1|JDate),data=dat3.2,family=poisson)
	m.4<-glmer(resp ~b.total.bright+treatment+ Offset2+(1|UnitBox)+(1|JDate),data=dat3.2,family=poisson)
	m.5<-glmer(resp ~b.total.bright+treatment+b.total.bright*treatment+ Offset2+(1|UnitBox)+(1|JDate),data=dat3.2,family=poisson)
	m.6<-glmer(resp ~r.h.theta+ Offset2+(1|UnitBox)+(1|JDate),data=dat3.2,family=poisson)
	m.7<-glmer(resp ~r.h.theta+treatment+ Offset2+(1|UnitBox)+(1|JDate),data=dat3.2,family=poisson)
	m.8<-glmer(resp ~r.h.theta+treatment+r.h.theta*treatment+ Offset2+(1|UnitBox)+(1|JDate),data=dat3.2,family=poisson)
	m.9<-glmer(resp ~r.r.achieved+ Offset2+(1|UnitBox)+(1|JDate),data=dat3.2,family=poisson)
	m.10<-glmer(resp ~r.r.achieved+treatment+ Offset2+(1|UnitBox)+(1|JDate),data=dat3.2,family=poisson)
	m.11<-glmer(resp ~r.r.achieved+treatment+r.r.achieved*treatment+ Offset2+(1|UnitBox)+(1|JDate),data=dat3.2,family=poisson)
	
	mod.output<-list(m.1,m.2,m.3,m.4,m.5,m.6,m.7,m.8,m.9,m.10,m.11)
	
	AICtab<-as.data.frame(modlist)
		for(j in 1:nrow(AICtab)){
			AICtab$AICc[j]<-AICc(mod.output[[j]])
			AICtab$LL[j]<-logLik(mod.output[[j]])
			AICtab$K[j]<-attr(logLik(mod.output[[j]]),"df")
		}
		minim<-min(AICtab$AICc)
		AICtab$D.AICc<-AICtab$AICc-minim
		AICtab$rellik<-exp(-.5* AICtab$D.AICc)
		sumAICs<-sum(AICtab$rellik)
		for(u in 1:nrow(AICtab)){
			AICtab$Wi[u]<-round(AICtab$rellik[u]/sumAICs,2)
		}
		AICtab<-AICtab[order(-AICtab$rellik),]
		
### Make a plot showing bib brightness by avg unique visitors per day

	post<-as.data.frame(mvrnorm(1000,fixef(m.5.vis),vcov(m.5.vis)))
	r<-seq(-3,3,0.1)
	mu.c<-sapply(r,function(z){mean(exp(post$"(Intercept)"+post$b.total.bright*z))})
	pdf("Output_Fig3.pdf",width=9,height=4.5)
	par(mfrow=c(1,2))
	dat3$All.u.j<-dat3$All.u+runif(nrow(dat3),-0.3,0.3)
	dat3$breast.j<-dat3$b.total.bright+runif(nrow(dat3),-0.1,0.1)
	plot(main.d$Avg.Uni.v~main.d$b.total.bright,
		pch=16,ylab="Average unique visitors per day",xaxt="n",yaxt="n",
		xlab="Mean breast brightness (%)",main="",col=col.alpha("slateblue",0.9),type="n",bty="n")
	axis(1,at=c(0,25,30,35,40,45,50,100))
	axis(2,at=c(-2,1,2,3,5))
	points(con$Avg.Uni.v~con$b.total.bright,pch=21,bg="gray40")
	points(lfr$Avg.Uni.v~lfr$b.total.bright,pch=21,bg="orange")
	points(hfr$Avg.Uni.v~hfr$b.total.bright,pch=21,bg="sky blue")
	abline(lm(con$Avg.Uni.v~con$b.total.bright),lwd=2,col="gray40")
	abline(lm(lfr$Avg.Uni.v~lfr$b.total.bright),lwd=2,col="orange")
	abline(lm(hfr$Avg.Uni.v~hfr$b.total.bright),lwd=2,col="skyblue")
	
	legend("topleft",c("Control","Low FR","High FR"),col=c("gray40","orange","sky blue"),bty="n",lwd=2,pch=21,pt.bg=c("gray40","orange","sky blue"))
	
	corner.label("(A)",1,1)
	#abline(lm(Avg.Uni.v~b.total.bright,data=main.d))
	#	for(i in 1:nrow(main.d)){
	#		lines(rep(main.d$b.total.bright[i],2),c(main.d$Avg.Uni.v[i]+(main.d$SD.Uni.v[i]/sqrt(main.d$n[i])),
	#			main.d$Avg.Uni.v[i]-(main.d$SD.Uni.v[i]/sqrt(main.d$n[i]))),col="gray40")
	#	}
	
### Make a plot showing bib brightness by avg unique trips per day
	dat3$Uni.t.j<-dat3$Uni.t+runif(nrow(dat3),-0.3,0.3)
	plot(main.d$Avg.Uni.t~main.d$b.total.bright,pch=16,col=col.alpha("slateblue",0.8),
		ylab="Average unique trips per day",type="n",
		xlab="Mean breast brightness (%)",main="",xaxt="n",yaxt="n",bty="n")
	axis(1,at=c(0,25,30,35,40,45,50,100))
	axis(2,at=c(-2,0,0.25,0.5,0.75,1,5))
	points(con$Avg.Uni.t~con$b.total.bright,pch=21,bg="gray40")
	points(lfr$Avg.Uni.t~lfr$b.total.bright,pch=21,bg="orange")
	points(hfr$Avg.Uni.t~hfr$b.total.bright,pch=21,bg="skyblue")
	corner.label("(B)",1,1)
	abline(lm(con$Avg.Uni.t~con$b.total.bright),lwd=2,col="gray40")
	abline(lm(lfr$Avg.Uni.t~lfr$b.total.bright),lwd=2,col="orange")
	abline(lm(hfr$Avg.Uni.t~hfr$b.total.bright),lwd=2,col="skyblue")
	
	legend("topleft",c("Control","Low FR","High FR"),col=c("gray40","orange","sky blue"),bty="n",lwd=2,pch=21,pt.bg=c("gray40","orange","sky blue"))
	
	
	#abline(lm(Avg.Uni.t~b.total.bright,data=main.d))
	dev.off()
	#	for(i in 1:nrow(main.d)){
	#		lines(rep(main.d$b.total.bright[i],2),c(main.d$Avg.Uni.t[i]+(main.d$SD.Uni.t[i]/sqrt(main.d$n[i])),
	#			main.d$Avg.Uni.t[i]-(main.d$SD.Uni.t[i]/sqrt(main.d$n[i]))),col="gray40")
	#	}


## Make a plot showing coloration and pre-treatment corticosterone

	par(mfrow=c(1,3))
	plot(main.d$b.total.bright,main.d$pre.base,col="slateblue",pch=16,ylab="Baseline corticosterone (ng/mL)",
		xlab="Average breast brightness (%)")
	plot(main.d$r.h.theta,main.d$pre.base,col="slateblue",pch=16,ylab="Baseline corticosterone (ng/mL)",
		xlab="Back theta")
	plot(main.d$r.r.achieved,main.d$pre.base,col="slateblue",pch=16,ylab="Baseline corticosterone (ng/mL)",
		xlab="Back r achieved")
		
	plot(main.d$b.total.bright,main.d$pre.s.resp,col="slateblue",pch=16,ylab="Stress induced cort (ng/mL)",
		xlab="Average breast brightness (%)")
	plot(main.d$r.h.theta,main.d$pre.s.resp,col="slateblue",pch=16,ylab="Stress induced cort (ng/mL)",
		xlab="Back theta")
	plot(main.d$r.r.achieved,main.d$pre.s.resp,col="slateblue",pch=16,ylab="Stress induced cort (ng/mL)",
		xlab="Back r achieved")
		
	pdf("Output_Fig4.pdf",width=9,height=4.5)
	par(mfrow=c(1,2))
	plot(main.d$r.r.achieved,main.d$pre.base,col="slateblue",pch=16,ylab="Baseline corticosterone (ng/mL)",
		xlab="Back r achieved")
	corner.label("(A)")
	abline(lm(main.d$pre.base~main.d$r.r.achieved))
	plot(main.d$b.total.bright,main.d$pre.s.resp,col="slateblue",pch=16,ylab="Stress response (ng/mL)",
		xlab="Average breast brightness (%)")
	corner.label("(B)")
	abline(lm(main.d$pre.s.resp~main.d$b.total.bright))
	dev.off()

	cor.test(main.d$b.total.bright,main.d$pre.base,use="pairwise.complete.obs")
	cor.test(main.d$r.h.theta,main.d$pre.base,use="pairwise.complete.obs")
	cor.test(main.d$r.r.achieved,main.d$pre.base,use="pairwise.complete.obs")
	cor.test(main.d$b.total.bright,main.d$pre.s.resp,use="pairwise.complete.obs")
	cor.test(main.d$r.h.theta,main.d$pre.s.resp,use="pairwise.complete.obs")
	cor.test(main.d$r.r.achieved,main.d$pre.s.resp,use="pairwise.complete.obs")

### Residual and fit plots for best models from above	
	EP<-residuals(m.6,type="pearson")
	plot(EP~fitted(m.6))
	qqnorm(EP)
	qqline(EP)
	plot(dat3$b.total.bright,EP)
	plot(dat3$Offset,EP)
	plot(dat3$ActivePIT,EP)
	plot(dat3$treatment,EP)
	
	
## Correlation plots for color for breast and back

pdf("Output_Fig_S1.pdf",width=8,height=8)
pairs(~b.total.bright+b.h.theta+b.h.phi+b.r.vec+b.r.achieved,data=main.d,
	labels=c("Brightness","Theta","Phi","r vec","r ach"))
dev.off()
pdf("Output_Fig_S2.pdf",width=8,height=8)
pairs(~r.total.bright+r.h.theta+r.h.phi+r.r.vec+r.r.achieved,data=main.d,
	labels=c("Brightness","Theta","Phi","r vec","r ach"))
dev.off()

pdf("Output_Fig_S4.pdf",width=4.5,height=4.5)
plot(main.d$rfid.days,main.d$total.v.u,col="slateblue",pch=16,ylab="Total unique visitors in season",
	xlab="Active RFID days")
abline(lm(main.d$total.v.u~main.d$rfid.days))
dev.off()

## active pit tags and RFID units

## NOT in paper, lines for each bird

## 	RFID days vs. total unique visitors

## Day in nest cycle and number of visitors

