data.generate=function(data,plotdim,process="Hom.Po",covr=list(elev=NULL,slope=NULL,aspect=NULL,curv=NULL,dentisy=NULL))

{
####data: plot data, with species name, gx and gy;
####plotdim:vector. Plotdim[1] is x; plotdim[2] is y;
####processes: 	character. All recognized processes are "Real", "Hom.Po", "Inhom.Po", "Hom.Th", "Inhom.Th"
####covr: list. Each element is an im object which could be generated by as.im()

library(spatstat)
  
 #set the windows
win=owin(c(0,plotdim[1]),c(0,plotdim[2]))
###S species richness
spname=as.character(unique(data$scientific_name))
S=length(spname)
data.new=data.frame(sp=NA,gx=NA,gy=NA)

if (process=="Real"){
  data.new=data.frame(sp=data$scientific_name,gx=data$gx,gy=data$gy)
  data.new=rbind(c(NA,NA,NA),data.new)
}

if (process=="Hom.Po"){
  
  for (i in 1:S){
    sp=data[which(data$scientific_name==spname[i]),]
    data.ppp=unique(ppp(x=sp$gx,y=sp$gy,window=win))
	repeat{
    data.ppm=ppm(data.ppp~1,Poisson())
    sp1=rmh.ppm(data.ppm)
	if (length(sp1$x)>0)
	break}
    data.new=rbind(data.new,data.frame(sp=rep(spname[i],times=sp1$n),gx=sp1$x,gy=sp1$y))
  }
}
  if (process=="Inhom.Po"){
    for (i in 1:S){
      sp=data[which(data$scientific_name==spname[i]),]
      data.ppp=unique(ppp(x=sp$gx,y=sp$gy,window=win))
      fu=formu(names(covr))
	  if (length(sp$gx)>=50){
      # using maximum likelihood method to estimate parameter
      data.ppm=ppm(data.ppp,fu,covariates=covr)
	  data.ppm=step(data.ppm)
      # simulate species distribution using the above fitted model
      sp1=rmh.ppm(data.ppm)
	  }
	  if (length(sp$gx)<50){
	  sp1=data.ppp
	  }
      data.new=rbind(data.new,data.frame(sp=rep(spname[i],times=sp1$n),gx=sp1$x,gy=sp1$y))
    }
  }
  if (process=="Hom.Th"){
    for (i in 1:S){
      sp=data[which(data$scientific_name==spname[i]),]
      data.ppp=unique(ppp(x=sp$gx,y=sp$gy,window=win))
	  if (length(sp$gx)>=50){
      sp1.kppm=kppm(data.ppp~1,"Thomas",statistic="K",method="mincon")
      sp1=rThomas(sp1.kppm$modelpar[1],sp1.kppm$modelpar[2],sp1.kppm$modelpar[3],win)
	  }
	  if (length(sp$gx)<50){
	 sp1=data.ppp
	  }
      data.new=rbind(data.new,data.frame(sp=rep(spname[i],times=sp1$n),gx=sp1$x,gy=sp1$y))
    }
  }
  if (process=="Inhom.Th"){
    for (i in 1:S){
      sp=data[which(data$scientific_name==spname[i]),]
      data.ppp=unique(ppp(x=sp$gx,y=sp$gy,window=win))
      fu=formu(names(covr))
	  if (length(sp$gx)>=50){
      sp1.kppm<-kppm(data.ppp,fu,"Thomas",data=covr,statistic="K",method="mincon")
	  repeat{
      sp1=rThomas(sp1.kppm$modelpar[1],sp1.kppm$modelpar[2],sp1.kppm$mu,win)
	  if (length(sp1$x)>0)
	  break}
	  }
	  if (length(sp$gx)<50){
	  sp1=data.ppp
	  }
      data.new=rbind(data.new,data.frame(sp=rep(spname[i],times=sp1$n),gx=sp1$x,gy=sp1$y))
    }
  }
# Formula construct

formu=function(name,del=NULL){
  l=length(name)
  for (i in 1:l){
    if (i==1) fu=paste("~",name[i])
    else fu=paste(fu,"+",name[i])
  }
  if (!is.null(del))
    fu=paste(fu,del)
  
  fu=as.formula(fu)
  return(fu)
}
data.new=data.new[-1,]
return(data.new)
}



