library(adegenet)
library(pegas)
library(vcfR)
library(gdsfmt)
library(SNPRelate)
library(ggplot2)
library(ggdendro)

snpgdsVCF2GDS("laredoensisIBS.vcf", "test.gds", method="copy.num.of.ref", ignore.chr.prefix="RAD_")
genofile <- snpgdsOpen("test.gds")
sample.id <- read.gdsn(index.gdsn(genofile, "sample.id"))
snpset <- snpgdsLDpruning(genofile, ld.threshold=0.2)
snpset.id <- unlist(unname(snpset))
ibs <- snpgdsIBS(genofile, snp.id=snpset.id)
