library(openxlsx)
setwd("~/Dropbox/Why bears hibernate?/Revised version_ProcRoyl/Dryad")
data <- read.xlsx("data.xlsx", sheet = 1, na.strings = "ND")
#running a double-log linear regression between DEEh and body mass (Fig 1)
mod1<-lm(log10(deeh)~log10(mb),data=data)
summary(mod1)
plot(log10(deeh)~log10(mb),data=data)
#BMR scaling to confirm 2/3 exponent
mod_bmr<-lm(log10(bmr1)~log10(mb),data=data)
summary(mod_bmr)
#running a semi-log regression between predicted energy savings and body mass, using BMR (Fig 2)
data <- read.xlsx("data.xlsx", sheet = 2, na.strings = "ND")
savingsBMR<-lm(savings~mb,data=data)
summary(savingsBMR)
plot(savings~log10(mb),data=data)
#running a semi-log regression between predicted energy savings and body mass, using DEE (Fig 3)
data <- read.xlsx("data.xlsx", sheet = 3, na.strings = "ND")
savingsDEE<-lm(savings~mb,data=data)
summary(savingsDEE)
plot(savings~log10(mb),data=data)
#running a double-log linear regression between cellular metabolism and body mass (Fig 4)
data <- read.xlsx("data.xlsx", sheet = 4, na.strings = "ND")
mod3<-lm(log10(cel_met)~log10(mb),data=data)
summary(mod3)
plot(log10(cel_met)~log10(mb),data=data)
#reanalyzing Ruf and Geiser (2015) data, using whole animal metabolic rate (Fig S1)
data <- read.xlsx("data.xlsx", sheet = 5, na.strings = "ND")
mod4<-lm(log10(TMRmin)~log10(mb),data=data)
summary(mod3)
plot(log10(TMRmin)~log10(mb),data=data)
#regressing predicting energy savings and body mass from Ruf and Geiser data (Fig S2)
data <- read.xlsx("data.xlsx", sheet = 6, na.strings = "ND")
mod5<-lm(savings~log10(mb),data=data)
summary(mod5)
plot(savings~log10(mb),data=data)
#Allometric regression with the five datapoints where both fat and lean mass consumption was directly measured
data <- read.xlsx("data.xlsx", sheet = 7, na.strings = "ND")
mod6<-lm(log10(deeh)~log10(mb),data=data)
summary(mod6)
plot(log10(deeh)~log10(mb),data=data)

###Reproducing the regression coefficients of Fig S4
data <- read.xlsx("data.xlsx", sheet = 10, na.strings = "ND")
Q_05<-lm(Q05~LogMB,data=data)
summary(Q_05)
Q_1<-lm(Q1~LogMB ,data=data)
summary(Q_1)
Q_15<-lm(Q15~LogMB ,data=data)
summary(Q_15)
Q_2<-lm(Q2~LogMB,data=data)
summary(Q_2)
Q_3<-lm(Q3~LogMB,data=data)
summary(Q_3)
Q_4<-lm(Q4~LogMB,data=data)
summary(Q_4)
Q_5<-lm(Q5~LogMB,data=data)
summary(Q_5)
Q_6<-lm(Q6~LogMB,data=data)
summary(Q_6)

