## Date: 9-25-2019
## Personal: Jagdeep Singh Sidhu (jagdeeproots@gmail.com)
## Purpose: This code:
##          1. Processes the Simroot output, combining multiple reps into single file for each location and wholeplot. There are three phenotypes (Shallow, intermediate, and deep) for
##             for each crop, namely Bean and Maize. Create a separate folder for each Phenotype which should have 100 subfolders (1 for each rep). Output files
##             are available as "Burridge_coring_20190508_outputs.tgz"

## Data needed: The data used here comes from Simroot output runs generated by Chris Black.For details look into the methods section of 
##              "An analysis of soil coring strategies to estimate root depth in maize (Zea mays) and common bean (Phaseolus vulgaris)"

###################
##Needed Packages##
#install.packages("plotrix")
library(plyr)
library(plotrix)
library("tripack")
library(tidyverse)
library(ggplot2)
library(reshape2)
library(stringr)

#Set the number of files
FileNumber <- 100

#################Editable variables - list ##################################
Root_type <- c("maize_shallow_", "maize_", "maize_deep_", "bean_shallow_", "bean_deep_", "bean_")

############## Big function to make all the other functions ##############
makefuncs <- function(){
 
### SET directory function ###
setdir <- function(){
directory <- paste("D:/DES/Penn State/roots lab/Coring_study_Jimmy/Simroot/Burridge_coring_20190508/",type, sep ="")

#Set Working Directory
setwd(paste(directory))
getwd()
message(paste("/working directory - ",directory))
}


MergeL1 <- function() {
  for (i in 1:FileNumber) {
    if (i == 1) {
      infolder <- paste(type,i,"/coringData_L1_tot.tab",sep="")
      infile <- paste(type,i,sep="")
      if (file.exists(infolder)) {
        tempfile <- read.delim(infolder)
        tempfile$run <- rep(infile,nrow(tempfile))
        NSRmerged <- tempfile
      }
      else {
        next
      }
      
    }
    
    else {
      infolder <- paste(type,i,"/coringData_L1_tot.tab",sep="")
      infile <- paste(type,i,sep="")
      if (file.exists(infolder)) {
        tempfile <- read.delim(infolder)
        tempfile$run <- rep(infile,nrow(tempfile))
        NSRmerged <- merge(NSRmerged,tempfile,sort = FALSE, all = TRUE)
      }
      else {
        next
      }
    }
  }
  
  write.csv(NSRmerged, paste(type,'coringData_L1_tot.csv',sep=""))
  message(paste("/Merged L1 for- ",type))
  }


MergeL2 <- function() {
  for (i in 1:FileNumber) {
    if (i == 1) {
      infolder <- paste(type,i,"/coringData_L2_tot.tab",sep="")
      infile <- paste(type,i,sep="")
      if (file.exists(infolder)) {
        tempfile <- read.delim(infolder)
        tempfile$run <- rep(infile,nrow(tempfile))
        NSRmerged <- tempfile
      }
      else {
        next
      }
      
    }
    
    else {
      infolder <- paste(type,i,"/coringData_L2_tot.tab",sep="")
      infile <- paste(type,i,sep="")
      if (file.exists(infolder)) {
        tempfile <- read.delim(infolder)
        tempfile$run <- rep(infile,nrow(tempfile))
        NSRmerged <- merge(NSRmerged,tempfile,sort = FALSE, all = TRUE)
      }
      else {
        next
      }
    }
  }
  
  write.csv(NSRmerged, paste(type,'coringData_L2_tot.csv',sep=""))
  message(paste("/Merged L2 for- ",type))
  }


MergeL3 <- function() {
  for (i in 1:FileNumber) {
    if (i == 1) {
      infolder <- paste(type,i,"/coringData_L3_tot.tab",sep="")
      infile <- paste(type,i,sep="")
      if (file.exists(infolder)) {
        tempfile <- read.delim(infolder)
        tempfile$run <- rep(infile,nrow(tempfile))
        NSRmerged <- tempfile
      }
      else {
        next
      }
      
    }
    
    else {
      infolder <- paste(type,i,"/coringData_L3_tot.tab",sep="")
      infile <- paste(type,i,sep="")
      if (file.exists(infolder)) {
        tempfile <- read.delim(infolder)
        tempfile$run <- rep(infile,nrow(tempfile))
        NSRmerged <- merge(NSRmerged,tempfile,sort = FALSE, all = TRUE)
      }
      else {
        next
      }
    }
  }
  
  write.csv(NSRmerged, paste(type,'coringData_L3_tot.csv',sep=""))
  message(paste("/Merged L3 for- ",type))
  }


MergeL4 <- function() {
  for (i in 1:FileNumber) {
    if (i == 1) {
      infolder <- paste(type,i,"/coringData_L4_tot.tab",sep="")
      infile <- paste(type,i,sep="")
      if (file.exists(infolder)) {
        tempfile <- read.delim(infolder)
        tempfile$run <- rep(infile,nrow(tempfile))
        NSRmerged <- tempfile
      }
      else {
        next
      }
      
    }
    
    else {
      infolder <- paste(type,i,"/coringData_L4_tot.tab",sep="")
      infile <- paste(type,i,sep="")
      if (file.exists(infolder)) {
        tempfile <- read.delim(infolder)
        tempfile$run <- rep(infile,nrow(tempfile))
        NSRmerged <- merge(NSRmerged,tempfile,sort = FALSE, all = TRUE)
      }
      else {
        next
      }
    }
  }
  
  write.csv(NSRmerged, paste(type,'coringData_L4_tot.csv',sep=""))
  message(paste("/Merged L4 for- ",type))
  }


MergeL5 <- function() {
  for (i in 1:FileNumber) {
    if (i == 1) {
      infolder <- paste(type,i,"/coringData_L5_tot.tab",sep="")
      infile <- paste(type,i,sep="")
      if (file.exists(infolder)) {
        tempfile <- read.delim(infolder)
        tempfile$run <- rep(infile,nrow(tempfile))
        NSRmerged <- tempfile
      }
      else {
        next
      }
      
    }
    
    else {
      infolder <- paste(type,i,"/coringData_L5_tot.tab",sep="")
      infile <- paste(type,i,sep="")
      if (file.exists(infolder)) {
        tempfile <- read.delim(infolder)
        tempfile$run <- rep(infile,nrow(tempfile))
        NSRmerged <- merge(NSRmerged,tempfile,sort = FALSE, all = TRUE)
      }
      else {
        next
      }
    }
  }
  
  write.csv(NSRmerged, paste(type,'coringData_L5_tot.csv',sep=""))
  message(paste("/Merged L5 for- ",type))
  }

MergeL6 <- function() {
  for (i in 1:FileNumber) {
    if (i == 1) {
      infolder <- paste(type,i,"/coringData_L6_tot.tab",sep="")
      infile <- paste(type,i,sep="")
      if (file.exists(infolder)) {
        tempfile <- read.delim(infolder)
        tempfile$run <- rep(infile,nrow(tempfile))
        NSRmerged <- tempfile
      }
      else {
        next
      }
      
    }
    
    else {
      infolder <- paste(type,i,"/coringData_L6_tot.tab",sep="")
      infile <- paste(type,i,sep="")
      if (file.exists(infolder)) {
        tempfile <- read.delim(infolder)
        tempfile$run <- rep(infile,nrow(tempfile))
        NSRmerged <- merge(NSRmerged,tempfile,sort = FALSE, all = TRUE)
      }
      else {
        next
      }
    }
  }
  MergeL6
  write.csv(NSRmerged,paste(type,'coringData_L6_tot.csv',sep=""))
  message(paste("/Merged L6 for- ",type))
  }



MergeCoreFiles <- function() {
  for (i in 1:6) {
    if (i == 1) {
      infile <- paste(type,"coringData_L",i,"_tot.csv",sep="")
      tempfile <- read.csv(infile)
      NSRmerged <- tempfile
      
      
    }
    
    else {
      infile <- paste(type,"coringData_L",i,"_tot.csv",sep="")
      if (file.exists(infile)) {
        tempfile <- read.csv(infile)
        NSRmerged <- merge(NSRmerged,tempfile,sort = FALSE, all = TRUE)
      }
      else {
        next
      }
    }
  }
  
  write.csv(NSRmerged, paste(type,'coringData_all.csv',sep=""))
  message(paste("/Merged all core files- ",type))
  }



MergeTabledOut <- function() {
  for (i in 1:FileNumber) {
    if (i == 1) {
      infolder <- paste(type,i,"/tabled_output.tab",sep="")
      infile <- paste(type,i,sep="")
      if (file.exists(infolder)) {
        tempfile <- read.delim(infolder)
        tempfile$run <- rep(infile,nrow(tempfile))
        NSRmerged <- tempfile
      }
      else {
        next
      }
      
    }
    
    else {
      infolder <- paste(type,i,"/tabled_output.tab",sep="")
      infile <- paste(type,i,sep="")
      if (file.exists(infolder)) {
        tempfile <- read.delim(infolder)
        tempfile$run <- rep(infile,nrow(tempfile))
        NSRmerged <- merge(NSRmerged,tempfile,sort = FALSE, all = TRUE)
      }
      else {
        next
      }
    }
  }
  
  write.csv(NSRmerged, paste(type,'tabled_output_merged.csv'))
  message(paste("/Merged tabledoutput for- ",type))
  }
message(paste("makefunctionranwell"))
        }


###########Call the functions just because they don't run otherwise in loop #####
makefuncs()

for (type  in Root_type) {
  
setdir()
MergeL1()
MergeL2()
MergeL3()
MergeL4()
MergeL5()
MergeL6()
MergeCoreFiles()
MergeTabledOut()
}

############################################
## After running this code, within in each phenotype (six phenotypes) folder you should have:
## 1. 6 files, each containing all the data for one of the six locations.
## 2. 1 file containing combined data of all the locations.
## 3. 1 file containing tabled output of all parameters for the Simroot run.
