## Date: 9-25-2019
## Personal: Jagdeep Singh Sidhu (jagdeeproots@gmail.com)
## Purpose: This code:
##          1. Takes output from "S1- Extract_simroot_data.R" file and extracts 40days data for each location and wholeplot. There are three phenotypes (Shallow, intermediate, and deep) for
##             for each crop, namely Bean and Maize. 
##          2. Also gives wholeplot average for each phenotype.

## Data needed: The data used here comes from Simroot output runs generated by Chris Black, which are then processed using "S1 - Extract_simroot_data.R" 
##              

###################
##Needed Packages##

## install.packages("plotrix") 
library(plyr)
library(plotrix)
library("tripack")
library(tidyverse)
library(ggplot2)
library(reshape2)
library(Rmisc) ## for summarySE
library(dplyr)

################################################################################################################
#############################   Editable variables - list  #####################################################
Root_type <- c("maize_shallow_", "maize_", "maize_deep_", "bean_shallow_", "bean_deep_", "bean_")

######################################################################################################
########################### nutshell function extracts 40 days data and wholeplot average ############
Main <- function(){

########## Whole plot average @@@@note its different for maize and bean #######
slice = 10
bean_across_row = 20
bean_along_row = 152.4
bean_plot =  bean_along_row * bean_across_row

maize_across_row = 40
maize_along_row = 152.4
maize_plot =  maize_along_row * maize_across_row

######################Core dimensions#######################
core_dia_cm = 4.4
core_area = 3.14*(2.2)^2
slice_height_cm = 10
core_slice_vol_cm3 = 3.14*core_dia_cm*slice_height_cm

########### setting directory ##################
directory <- paste("D:/DES/Penn State/roots lab/Coring_study_Jimmy/Simroot/Burridge_coring_20190508/",type, sep ="")

#Set Working Directory
setwd(paste(directory))
getwd()

################ Extract only 40 day data for each rep and location ###
all_days <- (read.csv(paste(type,'coringData_all.csv',sep="")) %>% 
               dplyr::rename(time = 'time.d.', Location = label)) 
  
  
if (type =="bean_"|type == "maize_"){ 
a <- as.data.frame(str_split_fixed(all_days$run,n =2, pattern = "_"))
colnames(a) <- c("crop", "Rep")
a$type <- "intermediate"
a <- a[,c("crop","type", "Rep")]
} else {a <- str_split_fixed(all_days$run,n =3, pattern = "_")
colnames(a) <- c("crop", "type", "Rep")
}

all_days1<- cbind(all_days, a)
forty_days <- mutate(subset(all_days1, time == "40"))
summary(forty_days)

## Change score names ##
forty_days$Location <- revalue(forty_days$Location, c("L1_tot"="1","L2_tot"="2", "L3_tot" = "3", "L4_tot" = "4", "L5_tot" = "5", "L6_tot" = "6"))

write.csv(forty_days,paste(type,'coringData_alllocs_40daysonly.csv',sep=""))

########################################################################################
########## Using whole plot average @@@@note its different for maize and bean #######
plot_area = "TBD"
if(type =="maize_shallow_"|type =="maize_deep_"| type == "maize_"){ plot_area <- maize_plot} else{plot_area <- bean_plot}  
print(paste(type, plot_area))

################ Extract whole plot average from tabled output #########
b <- read.csv(paste(type,"tabled_output_merged.csv"))

# keep space while renaming depths as its in simroot output
b$name= revalue(b$name, c("RootLengthProfile_00-10           "="-10","RootLengthProfile_10-20           "="-20", "RootLengthProfile_20-30           "="-30","RootLengthProfile_30-40           "="-40" ,"RootLengthProfile_40-50           "="-50", "RootLengthProfile_50-60           "="-60"))
b1 <- subset(b, time == "40")
b2 <- subset(b1, name %in% c("-10","-20","-30","-40","-50","-60")) 
b3 <- (b2 %>% dplyr::rename(Depth = 'name', Length.cm = value))

summary(b1)
summary(b2)

if (type =="bean_"|type == "maize_"){ 
  b4 <- as.data.frame(str_split_fixed(b3$run,n =2, pattern = "_"))
  colnames(b4) <- c("crop", "Rep")
  b4$type <- "intermediate"
  b4 <- b4[,c("crop","type", "Rep")]
} else {b4 <- str_split_fixed(b3$run,n =3, pattern = "_")
colnames(b4) <- c("crop", "type", "Rep")
}

b5 <- cbind(b3,b4)
b6 <- b5[,c(2:4,11)]
head(b6)
summary(b5)

b6$Depth = as.numeric(as.character(b6$Depth)) # first treat depth as character and then numeric because ggplot does not plot lines otherwise
b6$Rep = lapply(b6$Rep,as.factor)

### get RLD cm/cm3 ###
#b7 <- (b6 %>% mutate(RLD_cm_cm3 = Length.cm/plot_volumeperslice)) # this for RLDcm/cm3

b7 <- (b6 %>% mutate(Length.cm = (Length.cm/plot_area)*core_area, Location = "Wholeplot"))      
# write csv for anova
write.csv(as.matrix(b7), paste(type, "wholeplotfraov.csv"), row.names = FALSE)

## get summary for ggplot 
b7_summary <- summarySE(b7, measurevar="Length.cm", groupvars=c("Depth"))
b8_summary <- (b7_summary %>% mutate(Location = "Wholeplot"))

write.csv(as.data.frame(b8_summary), paste(type,"wholeplot_summary.csv"), row.names = FALSE)

###############################################################################################
#################### For getting the needed columns only #####################################
a <-read.csv(paste(type,"coringData_alllocs_40daysonly.csv", sep = ""))
head(a)
a1 = a[,-c(1:3,6:10,17:19)] 

## Melt the Depth column ##
a2 <- melt(data = a1 , id.vars = c("Location","time", "Rep"), value.name = "Length.cm", variable.name = "Depth")
summary(a2)

## change names of depth labels ##
a2$Depth = as.factor(a2$Depth)
a2$Depth= revalue(a2$Depth, c("X0.10"="-10","X10.20"="-20", "X20.30"="-30","X30.40"="-40" ,"X40.50"="-50", "X50.60"="-60"))
head(a2)

a2$Depth = as.numeric(as.character(a2$Depth))
a2$Rep = as.factor(a2$Rep)
summary(a2)

##### Summarize data ####
a2_summary <- summarySE(a2, measurevar="Length.cm", groupvars=c("Location","Depth"))
a2_summary
a2<<- a2
summary(a2)
a2$Location <- as.factor(a2$Location)
write.csv(a2,paste(type,"for_corecomparison.csv",sep="")) 

####read wholeplot average ##
wholeplot <- read.csv(paste(type,"wholeplot_summary.csv"))
wholeplot <<- wholeplot

loc_and_Wholeplot <- rbind(a2_summary,wholeplot)
write.csv(loc_and_Wholeplot, paste(type,"locandwholeplot.csv"))
loc_and_Wholeplot <<- loc_and_Wholeplot
}



######## Call function ##########
for (type in Root_type) {
  
Main ()}
warnings()

#############################################################################################
## After running this code, within in each phenotype (six phenotypes) folder you should have:
## 1. 1 file containing combined data of all the locations for 40 days time interval only.
## 2. 1 file containing Wholeplot summary.
## 3. 1 file containing needed extracted columns of all the locations for 40 days time interval as "type, for_corecomparison.csv".

