#This source code reproduces the results shown in subsection
#3.3 "Comparison between government periods"
#for non-dummy variables

#author: Andrea Falcon-Cortes

#Function necessary to compute the CI generated by the
#CDFs of the 1st period and compute how much of the CDFs of 
#the second period lie inside of the CI 
KS_interpolate <- function(x,x0,y0){
  
  y = vector("numeric", length = length(x))  
  
  for (i in 1:length(x)){
    j = 1
    if (x[i] <= x0[1]){
      y[i] = y0[1]
    } else if(x[i] >= x0[length(x0)]){
      y[i] = y0[length(y0)]
    } else{
      while(j < length(x0)){
        if(x[i] == x0[j]){
          y[i] = y0[j]
          j = length(x0)
        } else if(x0[j]<x[i] & x[i]<x0[j+1]){
          y[i] = y0[j]
          j = length(x0)
        }
        j = j+1 
      } 
    }
  }
  
  return(y)
}

#Necessary packages
library(dplyr)
library(tidyverse)
library(Rmisc)

#Data relative to contracts made from 2013 to 2020

#Upload the source list
data <- read.csv("~/RPS_Cont_2013-2020.csv", 
                 stringsAsFactors=FALSE)

#From the source list take only the non-dummy variables
#of type i) and ii)
fdata = subset(data, select = c(Status, DepID, ProvContID,
                                Year, BeginningWeek, EBWeeks,
                                Spending, T.Cont.Max, T.Spending.Max))

#To make the CDFs related to the comparison between
#government periods inside each class, it is necessary 
#to separate for years and classes. Here we only show and example
#for EFOS class. The same codes works for PCS and NC classes.

dataEPN_13.efos=fdata %>% filter(Year==2013 & Status == "EFOS")
dataEPN_14.efos=fdata %>% filter(Year==2014 & Status == "EFOS")
dataEPN_15.efos=fdata %>% filter(Year==2015 & Status == "EFOS")
dataEPN_16.efos=fdata %>% filter(Year==2016 & Status == "EFOS")
dataEPN_17.efos=fdata %>% filter(Year==2017 & Status == "EFOS")
dataEPN_18.efos=fdata %>% filter(Year==2018 & Status == "EFOS")

dataEPN_13.efos = subset(dataEPN_13.efos,select=-c(Year))
dataEPN_14.efos = subset(dataEPN_14.efos,select=-c(Year))
dataEPN_15.efos = subset(dataEPN_15.efos,select=-c(Year))
dataEPN_16.efos = subset(dataEPN_16.efos,select=-c(Year))
dataEPN_17.efos = subset(dataEPN_17.efos,select=-c(Year))
dataEPN_18.efos = subset(dataEPN_18.efos,select=-c(Year))

dataAMLO_19.efos=fdata %>% filter(Year==2019 & Status == "EFOS")
dataAMLO_20.efos=fdata %>% filter(Year==2020 & Status == "EFOS")

dataAMLO_19.efos = subset(dataAMLO_19.efos,select=-c(Year))
dataAMLO_20.efos = subset(dataAMLO_20.efos,select=-c(Year))

#Since variables of type i) are related to the fraction of contracts
#that satisfy certain property, and variables of type ii) are related
#to the fraction of buyers with certain features, it is necessary
#to make a list of the buyers and their features per class

dataEPN_13.efosDC = subset(dataEPN_13.efos, select = c(DepID,T.Cont.Max, T.Spending.Max))
dataEPN_14.efosDC = subset(dataEPN_14.efos, select = c(DepID,T.Cont.Max, T.Spending.Max))
dataEPN_15.efosDC = subset(dataEPN_15.efos, select = c(DepID,T.Cont.Max, T.Spending.Max))
dataEPN_16.efosDC = subset(dataEPN_16.efos, select = c(DepID,T.Cont.Max, T.Spending.Max))
dataEPN_17.efosDC = subset(dataEPN_17.efos, select = c(DepID,T.Cont.Max, T.Spending.Max))
dataEPN_18.efosDC = subset(dataEPN_18.efos, select = c(DepID,T.Cont.Max, T.Spending.Max))
dataAMLO_19.efosDC = subset(dataAMLO_19.efos, select = c(DepID,T.Cont.Max, T.Spending.Max))
dataAMLO_20.efosDC = subset(dataAMLO_20.efos, select = c(DepID,T.Cont.Max, T.Spending.Max))

dataEPN_13.efosDC = distinct(dataEPN_13.efosDC)
dataEPN_14.efosDC = distinct(dataEPN_14.efosDC)
dataEPN_15.efosDC = distinct(dataEPN_15.efosDC)
dataEPN_16.efosDC = distinct(dataEPN_16.efosDC)
dataEPN_17.efosDC = distinct(dataEPN_17.efosDC)
dataEPN_18.efosDC = distinct(dataEPN_18.efosDC)
dataAMLO_19.efosDC = distinct(dataAMLO_19.efosDC)
dataAMLO_20.efosDC = distinct(dataAMLO_20.efosDC)

#Generate the graphs and compute how much of the CDFs of the 2nd period 
#are inside of the CI of the 1st period. 

for(i in 4:ncol(dataEPN_13.efos)){
  l.main = paste("",sep = "")
  
  if(4<= i & i <= 6){
    cdf13 = environment(ecdf(dataEPN_13.efos[,i]))
    cdf14 = environment(ecdf(dataEPN_14.efos[,i]))
    cdf15 = environment(ecdf(dataEPN_15.efos[,i]))
    cdf16 = environment(ecdf(dataEPN_16.efos[,i]))
    cdf17 = environment(ecdf(dataEPN_17.efos[,i]))
    cdf18 = environment(ecdf(dataEPN_18.efos[,i]))
    
    cdf19 = environment(ecdf(dataAMLO_19.efos[,i]))
    cdf20 = environment(ecdf(dataAMLO_20.efos[,i]))
    
    x.min = min(cdf13$x,cdf14$x,cdf15$x,cdf16$x,cdf17$x,cdf18$x)
    x.max = max(cdf13$x,cdf14$x,cdf15$x,cdf16$x,cdf17$x,cdf18$x)
    
    if(names(dataEPN_13.efos)[i] == "Spending"){
      x.max = 2e+06
    }
    
    if(names(dataEPN_13.efos)[i] == "EBWeeks"){
      x.max = 60
    }
    
    #x.max = max(cdf20$x)
    
    x = seq(x.min, x.max, length.out = 700)
    
    y13 = KS_interpolate(x, cdf13$x, cdf13$y)
    y14 = KS_interpolate(x, cdf14$x, cdf14$y)
    y15 = KS_interpolate(x, cdf15$x, cdf15$y)
    y16 = KS_interpolate(x, cdf16$x, cdf16$y)
    y17 = KS_interpolate(x, cdf17$x, cdf17$y)
    y18 = KS_interpolate(x, cdf18$x, cdf18$y)
    
    y19 = KS_interpolate(x, cdf19$x, cdf19$y)
    y20 = KS_interpolate(x, cdf20$x, cdf20$y)
    
    CI.cdf.y = matrix(NA, 3, length(x))
    
    for(j in 1:length(x)){
      
      y = c(y13[j], y14[j], y15[j], y16[j], y17[j], y18[j])
      
      CI.cdf.y[1,j] = as.numeric(CI(y, ci = 0.99)[[1]])
      CI.cdf.y[2,j] = as.numeric(CI(y, ci = 0.99)[[2]])
      CI.cdf.y[3,j] = as.numeric(CI(y, ci = 0.99)[[3]])
      
    }
    
    in.ci.19 = length(which(y19 >= (CI.cdf.y[3,]) & y19 <= (CI.cdf.y[1,])))/length(y19)
    in.ci.20 = length(which(y20 >= (CI.cdf.y[3,]) & y20 <= (CI.cdf.y[1,])))/length(y20)
    
    print(c(names(dataEPN_13.efos)[i], in.ci.19*100, in.ci.20*100))
    
    y.min.cdf = min (cdf13$y,cdf14$y,cdf15$y,cdf16$y,cdf17$y,cdf18$y,cdf19$y,cdf20$y,
                     CI.cdf.y[3,])
    y.max.cdf = max (cdf13$y,cdf14$y,cdf15$y,cdf16$y,cdf17$y,cdf18$y,cdf19$y,cdf20$y,
                     CI.cdf.y[1,])
    
    name.g = paste("EFOS-",names(dataEPN_13.efos)[i],"-CDF.png", sep = "")
    png(name.g, width = 5, height = 5, units = "in", res = 300)
    
    plot(ecdf(dataAMLO_20.efos[,i]), main = l.main, xlim = c(x.min, x.max),
         ylim = c(y.min.cdf,y.max.cdf), col = "purple",
         lwd  = 1 ,lty = 2,
         xlab = names(dataEPN_13.efos)[i], ylab = "CDF", verticals = T, 
         col.01line = NULL, do.points = F, las = 1, cex.axis = 1.0, cex.lab  =1.25)
    polygon(c(x, rev(x)), c(CI.cdf.y[3,], rev(CI.cdf.y[1,])), 
            col = adjustcolor("green", alpha.f = 0.25), border = NA)
    lines(x, CI.cdf.y[2,], col = "orange", lty = 3, lwd = 2)
    lines(ecdf(dataAMLO_19.efos[,i]), col = adjustcolor("purple", alpha.f = 0.4),
          lty = 1, lwd = 3,
          verticals = T, col.01line=NULL, do.points = F)
    lines(ecdf(dataAMLO_20.efos[,i]), col = "purple", lty = 2, lwd = 1,
          verticals = T, col.01line=NULL, do.points = F)
    
    
    if(names(dataEPN_13.efos)[i] == "EndingWeek"){
      
      legend("topleft", col = c("orange", adjustcolor("purple", alpha.f = 0.4), "purple"),
             lty = c(3,1,2), lwd = c(2,3,1),
             legend = c("Mean 1st period", "2019", "2020"),
             cex = 1.0, bty = "n", ncol = 1)
    }
    
    dev.off()
  } else{
    if (i== 8){  
      for (j in 2:3){
        
        cdf13 = environment(ecdf(dataEPN_13.efosDC[,j]))
        cdf14 = environment(ecdf(dataEPN_14.efosDC[,j]))
        cdf15 = environment(ecdf(dataEPN_15.efosDC[,j]))
        cdf16 = environment(ecdf(dataEPN_16.efosDC[,j]))
        cdf17 = environment(ecdf(dataEPN_17.efosDC[,j]))
        cdf18 = environment(ecdf(dataEPN_18.efosDC[,j]))
        
        cdf19 = environment(ecdf(dataAMLO_19.efosDC[,j]))
        cdf20 = environment(ecdf(dataAMLO_20.efosDC[,j]))
        
        x.min = min(cdf13$x,cdf14$x,cdf15$x,cdf16$x,cdf17$x,cdf18$x)
        x.max = max(cdf13$x,cdf14$x,cdf15$x,cdf16$x,cdf17$x,cdf18$x)
        
        
        if(names(dataEPN_13.efosDC)[j] == "T.Spending.Max"){
          x.max = 5e+07
        }
        
        if(names(dataEPN_13.efosDC)[j] == "T.Cont.Max"){
          x.max = 500
        }
        
        #x.max = max(cdf20$x)
        
        x = seq(x.min, x.max, length.out = 700)
        
        y13 = KS_interpolate(x, cdf13$x, cdf13$y)
        y14 = KS_interpolate(x, cdf14$x, cdf14$y)
        y15 = KS_interpolate(x, cdf15$x, cdf15$y)
        y16 = KS_interpolate(x, cdf16$x, cdf16$y)
        y17 = KS_interpolate(x, cdf17$x, cdf17$y)
        y18 = KS_interpolate(x, cdf18$x, cdf18$y)
        
        y19 = KS_interpolate(x, cdf19$x, cdf19$y)
        y20 = KS_interpolate(x, cdf20$x, cdf20$y)
        
        CI.cdf.y = matrix(NA, 3, length(x))
        
        for(k in 1:length(x)){
          
          y = c(y13[k], y14[k], y15[k], y16[k], y17[k], y18[k])
          
          CI.cdf.y[1,k] = as.numeric(CI(y, ci = 0.99)[[1]])
          CI.cdf.y[2,k] = as.numeric(CI(y, ci = 0.99)[[2]])
          CI.cdf.y[3,k] = as.numeric(CI(y, ci = 0.99)[[3]])
          
        }
        
        in.ci.19 = length(which(y19 >= (CI.cdf.y[3,]) & y19 <= (CI.cdf.y[1,])))/length(y19)
        in.ci.20 = length(which(y20 >= (CI.cdf.y[3,]) & y20 <= (CI.cdf.y[1,])))/length(y20)
        
        print(c(names(dataEPN_13.efosDC)[j], in.ci.19*100, in.ci.20*100))
        
        y.min.cdf = min (cdf13$y,cdf14$y,cdf15$y,cdf16$y,cdf17$y,cdf18$y,cdf19$y,cdf20$y,
                         CI.cdf.y[3,])
        y.max.cdf = max (cdf13$y,cdf14$y,cdf15$y,cdf16$y,cdf17$y,cdf18$y,cdf19$y,cdf20$y,
                         CI.cdf.y[1,])
        
        name.g = paste("EFOS-",names(dataEPN_13.efosDC)[j],"-CDF.png", sep = "")
        png(name.g, width = 5, height = 5, units = "in", res = 300)
        
        plot(ecdf(dataAMLO_20.efosDC[,j]),main = l.main, xlim = c(x.min, x.max),
             ylim = c(y.min.cdf,y.max.cdf), col = "purple",
             lty = 2, lwd=1,
             xlab = names(dataEPN_13.efosDC)[j], ylab = "CDF", verticals = T,
             col.01line = NULL, do.points = F, cex.axis = 1, cex.lab = 1.25, las = 1)
        polygon(c(x, rev(x)), c(CI.cdf.y[3,], rev(CI.cdf.y[1,])), 
                col = adjustcolor("green", alpha.f = 0.25), border = NA)
        lines(x, CI.cdf.y[2,], col = "orange", lty = 3, lwd = 2)
        lines(ecdf(dataAMLO_19.efosDC[,j]), col = adjustcolor("purple", alpha.f = 0.4),
              lty = 1, lwd = 3,
              verticals = T, col.01line = NULL, do.points = F)
        lines(ecdf(dataAMLO_20.efosDC[,j]), col = "purple", lty = 2, lwd = 1,
              verticals = T, col.01line = NULL, do.points = F)
        
        
        dev.off()
        
      }
    }
  }
}
