#START####

#R code to recreate analyses from: "Testing drivers of acoustic divergence in cicadas (Cicadidae: Tettigettalna)”
#Raquel Mendes, Vera L. Nunes, Eduardo Marabuto, Gonçalo J. Costa, Sara E. Silva, Octávio S. Paulo, Paula C. Simões
#Journal of Evolutionary Biology (MS number: JEB-2022-00290)

#The exact results generated by this code for the single-rate models and multi-regime models of evolution will differ from those in the paper
#and between each time the script is run. This is due to the nature of the analysis and is not problematic
#the results should be qualitatively the same and the conclusions equivalent.
#the phylogenetic signal, PGLS analysis and phylomorphospace  results should be identical to those in the paper

#contact Raquel Mendes: raquelgmende@sgmail.com #


####>> Libraries ####
library(ape)
library(gdata)
library(dplyr)
library(phytools)
library(caper)
library(geiger)
library(OUwie)

####>> Upload data ####
data <- read.csv("all_variables.csv", sep=",")
tree <- read.tree("Ptree.tre")

## Plot phylogenetic tree and re-order data file by tree tips 
plot(tree)
data$SP <- reorder.factor(data$SP, new.order=tree$tip.label)
data <- data %>% arrange(SP)


rownames(data) <- data$SP
tetti <- comparative.data(tree, data, SP, vcv=TRUE) #combine phylogeny with dataset 

####>> Phylogenetic signal ####
# results show in Table 2 

####>>> Continuous Variables  ####
# calculates Pagels lambda for each continuous variable 
# data is log or square transformed inside the function 
# standard error of each variables is used 
PS.CD <- phylosig(tree, log(data$CD), method = "lambda", test=TRUE, se=data$se_CD)
PS.NE <- phylosig(tree, log(data$NE), method = "lambda", test=TRUE, se=data$se_NE)
PS.ER <- phylosig(tree, log(data$ER), method = "lambda", test=TRUE, se=data$se_ER)
PS.ED <- phylosig(tree, log(data$ED), method = "lambda", test=TRUE, se=data$se_ED)
PS.ID <- phylosig(tree, log(data$ID), method = "lambda", test=TRUE, se=data$se_ID)
PS.DF <- phylosig(tree, sqrt(data$DF), method ="lambda", test=TRUE, se=data$se_DF)
PS.PL <- phylosig(tree, log(data$PL), method = "lambda", test=TRUE, se=data$se_PL)


####>>> Binary variables ####
# calculates D parameter for the two binary variables, calling site (Vegetation) 
# and NDVI. With 10000 permutations 
set.seed(7)
PS_Vege <- phylo.d(data,tree, SP, Vegetation, permut=10000)
PS_NDVI <- phylo.d(data,tree, SP, NDVI_d, permut=10000)


####>> PGLS ####
####>>> Correlation between each acoustic variables and pronotum length ####
# results show in Table 3 

# Models 
pgls_CD.PL <- pgls(log(CD) ~ log(PL), tetti, lambda="ML")
pgls_NE.PL <- pgls(log(NE) ~ log(PL), tetti, lambda="ML")
pgls_ER.PL <- pgls(log(ER) ~ log(PL), tetti, lambda="ML")
pgls_ED.PL <- pgls(log(ED) ~ log(PL), tetti, lambda="ML")
pgls_ID.PL <- pgls(log(ID) ~ log(PL), tetti, lambda="ML")
pgls_DF.PL <- pgls(sqrt(DF) ~ log(PL), tetti, lambda="ML")

# Results 
summary.pgls(pgls_CD.PL)
summary.pgls(pgls_NE.PL)
summary.pgls(pgls_ER.PL)
summary.pgls(pgls_ER.PL)
summary.pgls(pgls_ID.PL)
summary.pgls(pgls_DF.PL)

# Inspected the distribution of the residuals to assess 
# their normality and homogeneity (Freckleton, 2009) 
plot(pgls_CD.PL)
plot(pgls_NE.PL)
plot(pgls_ER.PL)
plot(pgls_ER.PL)
plot(pgls_ID.PL)
plot(pgls_DF.PL)

####>>> Correlation between each acoustic variables and bioclimatic variables ####
# results show in Table 5 and Supplemental Information Table S4 

pgls19 <- pgls(sqrt(DF) ~ bio1, tetti, lambda="ML")   
pgls20 <- pgls(sqrt(DF) ~ bio2, tetti, lambda="ML")  
pgls21 <- pgls(sqrt(DF) ~ bio3, tetti, lambda="ML")  
pgls22 <- pgls(sqrt(DF) ~ bio4, tetti, lambda="ML") 
pgls23 <- pgls(sqrt(DF) ~ bio5, tetti, lambda="ML") 
pgls24 <- pgls(sqrt(DF) ~ bio8, tetti, lambda="ML") 
pgls25 <- pgls(sqrt(DF) ~ bio9, tetti, lambda="ML") 
pgls26 <- pgls(sqrt(DF) ~ bio12, tetti, lambda="ML") 
pgls27 <- pgls(sqrt(DF) ~ bio18, tetti, lambda="ML") 


####>>> Correlation between each acoustic variables and NDVI (high/low) ####
# results show in Table 6 

# Models 
pgls_CD.NDVI <- pgls(log(CD) ~ NDVI_d, tetti, lambda="ML")
pgls_NE.NDVI <- pgls(log(NE) ~ NDVI_d, tetti, lambda="ML")
pgls_ER.NDVI <- pgls(log(ER) ~ NDVI_d, tetti, lambda="ML")
pgls_ED.NDVI <- pgls(log(ED) ~ NDVI_d, tetti, lambda="ML")
pgls_ID.NDVI <- pgls(log(ID) ~ NDVI_d, tetti, lambda="ML")
pgls_DF.NDVI <- pgls(sqrt(DF) ~ NDVI_d, tetti, lambda="ML")


# Results 
summary.pgls(pgls_CD.NDVI)
summary.pgls(pgls_NE.NDVI)
summary.pgls(pgls_ER.NDVI)
summary.pgls(pgls_ED.NDVI)
summary.pgls(pgls_ID.NDVI)
summary.pgls(pgls_DF.NDVI)

# Inspected the distribution of the residuals to assess 
# their normality and homogeneity (Freckleton, 2009) 
plot(pgls_CD.NDVI)
plot(pgls_NE.NDVI)
plot(pgls_ER.NDVI)
plot(pgls_ED.NDVI)
plot(pgls_ID.NDVI)
plot(pgls_DF.NDVI)


####>>> Correlation between each acoustic variables and  calling site (shrubby/arboreal) ###
# results show in Table 7 

# Models 
pgls_CD.Veg <- pgls(log(CD) ~ Vegetation, tetti, lambda="ML")
pgls_NE.Veg <- pgls(log(NE) ~ Vegetation, tetti, lambda="ML")
pgls_ER.Veg <- pgls(log(ER) ~ Vegetation, tetti, lambda="ML")
pgls_ED.Veg <- pgls(log(ED) ~ Vegetation, tetti, lambda="ML")
pgls_ID.Veg <- pgls(log(ID) ~ Vegetation, tetti, lambda="ML")
pgls_DF.Veg <- pgls(sqrt(DF) ~ Vegetation, tetti, lambda="ML")


# Results 
summary.pgls(pgls_CD.Veg)
summary.pgls(pgls_NE.Veg)
summary.pgls(pgls_ER.Veg)
summary.pgls(pgls_ED.Veg)
summary.pgls(pgls_ID.Veg)
summary.pgls(pgls_DF.Veg)

# Inspected the distribution of the residuals to assess 
# their normality and homogeneity (Freckleton, 2009) 
plot(pgls_CD.Veg)
plot(pgls_NE.Veg)
plot(pgls_ER.Veg)
plot(pgls_ED.Veg)
plot(pgls_ID.Veg)
plot(pgls_DF.Veg)



####>> Mode of evolution ####
####>>> Single-rate models ####
####>>>> CD ####
EB1 <- fitContinuous(tree,log(data[4]), model = "EB", SE=data[34])  
BM1 <- fitContinuous(tree,log(data[4]), model= "BM", SE=data[34])  
OU1 <- fitContinuous(tree,log(data[4]), model = "OU", bounds=list(alpha=c(0,20)), SE=data[34])  

aic1<-c(EB1$opt$aicc, BM1$opt$aicc, OU1$opt$aicc)
names(aic1)<-c("EB1", "BM1", "OU1")
aic.w(aic1)

####>>>> NE ####
EB2<-fitContinuous(tree,log(data[5]), model = "EB",SE=data[35])  
BM2<-fitContinuous(tree,log(data[5]), model= "BM",SE=data[35])  
OU2<-fitContinuous(tree,log(data[5]), model = "OU",bounds=list(alpha=c(0,20)), SE=data[35])  

aic2<-c(EB2$opt$aicc, BM2$opt$aicc, OU2$opt$aicc)
names(aic2)<-c("EB2", "BM2", "OU2")
aic.w(aic2)

#####>>>> ER ####
EB3<-fitContinuous(tree,log(data[6]), model = "EB",bounds=list(alpha=c(0,20)))  
BM3<-fitContinuous(tree,log(data[6]), model= "BM",SE=data[36])  
OU3<-fitContinuous(tree,log(data[6]), model = "OU",SE=data[36])  

aic3<-c(EB3$opt$aicc, BM3$opt$aicc, OU3$opt$aicc)
names(aic3)<-c("EB3", "BM3", "OU3")
aic.w(aic3)

####>>>> ED ####
EB4<-fitContinuous(tree,log(data[7]), model = "EB",bounds=list(alpha=c(0,20)),SE=data[37])  
BM4<-fitContinuous(tree,log(data[7]), model= "BM",SE=data[37])  
OU4<-fitContinuous(tree,log(data[7]), model = "OU",SE=data[37])  

aic4<-c(EB4$opt$aicc, BM4$opt$aicc, OU4$opt$aicc)
names(aic4)<-c("EB4", "BM4", "OU4")
aic.w(aic4)

####>>>> ID ####
EB5<-fitContinuous(tree,log(data[8]), model = "EB",SE=data[38])  
BM5<-fitContinuous(tree,log(data[8]), model= "BM",SE=data[38])  
OU5<-fitContinuous(tree,log(data[8]), model = "OU",SE=data[38])  

aic5<-c(EB5$opt$aicc, BM5$opt$aicc, OU5$opt$aicc)
names(aic5)<-c("EB5", "BM5", "OU5")
aic.w(aic5)

####>>>> DF ####
EB6<-fitContinuous(tree,sqrt(data[9]), model = "EB",SE=data[39])  
BM6<-fitContinuous(tree,sqrt(data[9]), model= "BM",SE=data[39])  
OU6<-fitContinuous(tree,sqrt(data[9]), model = "OU",SE=data[39])  

aic6<-c(EB6$opt$aicc, BM6$opt$aicc, OU6$opt$aicc)
names(aic6)<-c("EB6", "BM6", "OU6")
aic.w(aic6)


####>>> Multi-regime models using OUwie ####
####>>>> Calling site:Vegetation ####
# Plot the distribution of calling site on tips of the tree #

colr<-rep("red", length(data[,1]))
colr[data[,2]==0]<-"black"

names(colr)<-data[,1] 
colr<-colr[tree$tip.label]
plot(tree, show.tip.label=F)

tiplabels(pch=16, col=colr)

# Assign nodes or branches to a calling site category #
eco <- as.factor(data$Vegi)
names(eco) <- data[,1]

ecoTree <- rerootingMethod(tree, eco, model="ER")

# Assign the state with the highest likelihood to each node #
ecotree<-tree
ecotree$node.label<-vector()
for (i in 1:tree$Nnode)ecotree$node.label[i]<-names(ecoTree$marginal.anc[i,])[ecoTree$marginal.anc[i,]==max(ecoTree$marginal.anc[i,])]

# Plot  the nodes on the tree #
nodecolr<-rep("green", length=tree$Nnode)
nodecolr[ecotree$node.label==0]<-"purple"

plot(tree, show.tip.label=F)
tiplabels(pch=16, col=colr)
nodelabels(pch=16, col=nodecolr)

####>>>> NDVI ####
# Plot the distribution of calling site on tips of the tree #
colr<-rep("red", length(data[,1]))
colr[data[,40]=="high"]<-"black"

names(colr)<-data[,1] 
colr<-colr[tree$tip.label]
plot(tree, show.tip.label=F)

tiplabels(pch=16, col=colr)

# Assign nodes or branches to a calling site category #
eco2 <- as.factor(data$NDVI_d)
names(eco2) <- data[,1]

ecoTree2 <- rerootingMethod(tree, eco2, model="ER")

# Assign the state with the highest likelihood to each node #
ecotree2<-tree
ecotree2$node.label<-vector()
for (i in 1:tree$Nnode)ecotree2$node.label[i]<-names(ecoTree2$marginal.anc[i,])[ecoTree2$marginal.anc[i,]==max(ecoTree2$marginal.anc[i,])]

# Plot  the nodes on the tree #
nodecolr<-rep("green", length=tree$Nnode)
nodecolr[ecotree2$node.label==0]<-"purple"

plot(tree, show.tip.label=F)
tiplabels(pch=16, col=colr)
nodelabels(pch=16, col=nodecolr)


####>>>> Fit models ####
CD_df<-data.frame(data[,1], eco, log(data[,4]), data[34])
NE_df<-data.frame(data[,1], eco, log(data[,5]), data[35])
ER_df<-data.frame(data[,1], eco, log(data[,6]), data[36])
ED_df<-data.frame(data[,1], eco, log(data[,7]), data[37])
ID_df<-data.frame(data[,1], eco, log(data[,8]), data[38])
DF_df<-data.frame(data[,1], eco, sqrt(data[,9]), data[39])

CD_dfN<-data.frame(data[,1], eco2, log(data[,4]), data[34])
NE_dfN<-data.frame(data[,1], eco2, log(data[,5]), data[35])
ER_dfN<-data.frame(data[,1], eco2, log(data[,6]), data[36])
ED_dfN<-data.frame(data[,1], eco2, log(data[,7]), data[37])
ID_dfN<-data.frame(data[,1], eco2, log(data[,8]), data[38])
DF_dfN<-data.frame(data[,1], eco2, sqrt(data[,9]), data[39])



#>>> CD ####
fitOUMV1<-OUwie(ecotree, CD_df,model="OUMV", mserr="known",diagn = TRUE)
fitBMS1<-OUwie(ecotree, CD_df,model="BMS", mserr="known",root.station=FALSE,diagn = TRUE)
fitOUMV1N<-OUwie(ecotree2, CD_dfN,model="OUMV", mserr="known",diagn = TRUE)
fitBMS1N<-OUwie(ecotree2, CD_dfN,model="BMS", mserr="known",root.station=FALSE,diagn = TRUE)

ouwie_aic1<-c(fitBMS1$AICc, fitOUMV1$AICc,fitOUMV1N$AICc,fitBMS1N$AICc)
names(ouwie_aic1)<-c("fitBMS1", "fitOUMV1", "fitOUMV1N", "fitBMS1N")
aic.w(ouwie_aic1)

#>>> NE ####
fitOUMV2<-OUwie(ecotree, NE_df,model="OUMV", mserr="known",diagn = TRUE)
fitBMS2<-OUwie(ecotree, NE_df,model="BMS", mserr="known", root.station=FALSE,diagn = TRUE)
fitOUMV2N<-OUwie(ecotree2, NE_dfN,model="OUMV", mserr="known",diagn = TRUE)
fitBMS2N<-OUwie(ecotree2, NE_dfN,model="BMS", mserr="known",root.station=FALSE,diagn = TRUE)

ouwie_aic2<-c(fitBMS2$AICc, fitOUMV2$AICc,fitOUMV2N$AICc,fitBMS2N$AICc)
names(ouwie_aic2)<-c("fitBMS2", "fitOUMV2","fitOUMV2N", "fitBMS2N")
aic.w(ouwie_aic2)

#>>> ER ####
fitOUMV3<-OUwie(ecotree, ER_df,model="OUMV", mserr="known",diagn = TRUE)
fitBMS3<-OUwie(ecotree, ER_df,model="BMS", mserr="known",root.station=FALSE,diagn = TRUE)
fitOUMV3N<-OUwie(ecotree2, ER_dfN,model="OUMV", mserr="known",diagn = TRUE)
fitBMS3N<-OUwie(ecotree2, ER_dfN,model="BMS", mserr="known",root.station=FALSE,diagn = TRUE)

ouwie_aic3<-c(fitBMS3$AICc, fitOUMV3$AICc,fitOUMV3N$AICc,fitBMS3N$AICc)
names(ouwie_aic3)<-c("fitBMS3", "fitOUMV3","fitOUMV3N", "fitBMS3N")
aic.w(ouwie_aic3)

#>>> ED ####
fitOUMV4<-OUwie(ecotree, ED_df,model="OUMV", mserr="known",diagn = TRUE)
fitBMS4<-OUwie(ecotree, ED_df,model="BMS", mserr="known",root.station=FALSE,diagn = TRUE)
fitOUMV4N<-OUwie(ecotree2, ED_dfN,model="OUMV", mserr="known",diagn = TRUE)
fitBMS4N<-OUwie(ecotree2, ED_dfN,model="BMS", mserr="known",root.station=FALSE,diagn = TRUE)


ouwie_aic4<-c(fitBMS4$AICc, fitOUMV4$AICc,fitOUMV4N$AICc,fitBMS4N$AICc)
names(ouwie_aic4)<-c("fitBMS4", "fitOUMV4","fitOUMV4N", "fitBMS4N")
aic.w(ouwie_aic4)

#>>> ID ####
fitOUMV5<-OUwie(ecotree, ID_df,model="OUMV", mserr="known",diagn = TRUE)
fitBMS5<-OUwie(ecotree, ID_df,model="BMS", mserr="known",root.station=FALSE,diagn = TRUE)
fitOUMV5N<-OUwie(ecotree2, ID_dfN,model="OUMV", mserr="known",diagn = TRUE)
fitBMS5N<-OUwie(ecotree2, ID_dfN,model="BMS", mserr="known",root.station=FALSE,diagn = TRUE)


ouwie_aic5<-c(fitBMS5$AICc, fitOUMV5$AICc,fitOUMV5N$AICc,fitBMS5N$AICc)
names(ouwie_aic5)<-c("fitBMS5", "fitOUMV5","fitOUMV5N", "fitBMS5N")
aic.w(ouwie_aic5)

#>>> DF ####
fitOUMV6<-OUwie(ecotree, DF_df,model="OUMV", mserr="known", diagn = TRUE)
fitBMS6<-OUwie(ecotree, DF_df,model="BMS", mserr="known",root.station=FALSE, diagn = TRUE)
fitOUMV6N<-OUwie(ecotree2, DF_dfN,model="OUMV", mserr="known",diagn = TRUE)
fitBMS6N<-OUwie(ecotree2, DF_dfN,model="BMS", mserr="known",root.station=FALSE,diagn = TRUE)


ouwie_aic6<-c(fitBMS6$AICc, fitOUMV6$AICc,fitOUMV6N$AICc,fitBMS6N$AICc)
names(ouwie_aic6)<-c("fitBMS6", "fitOUMV6","fitOUMV6N", "fitBMS6N")
aic.w(ouwie_aic6)

#>> Model selection ####
AIC1<-c(aic1,ouwie_aic1)
AIC2<-c(aic2,ouwie_aic2)
AIC3<-c(aic3,ouwie_aic3)
AIC4<-c(aic4,ouwie_aic4)
AIC5<-c(aic5,ouwie_aic5)
AIC6<-c(aic6,ouwie_aic6)

AICtotal <- rbind(AIC1, AIC2, AIC3, AIC4, AIC5, AIC6)

CD<-aic.w(AIC1)
NE<-aic.w(AIC2)
ER<-aic.w(AIC3)
ED<-aic.w(AIC4)
ID<-aic.w(AIC5)
DF<-aic.w(AIC6)

AICWtotal <- rbind(CD, NE, ER, ED, ID, DF)

AICWtotal


#END####


































